#!/bin/sh
#
# Apply the workaround for the Fujitsu Fortran runtime memory leak
# (https://www.fugaku.r-ccs.riken.jp/bug/20260120_01).
#
# Run once from anywhere, before ./regen.sh && ./configure:
#
#     sh patches/fujitsu_memleak.sh
#
# The script is idempotent, re-running it on an already patched tree does
# nothing.  It is deliberately split in four parts, so that the churn of
# the surrounding code does not invalidate the workaround:
#
#   1. The workaround module itself and its entry in neko_fortran_SOURCES,
#      carried as a context diff.  A new file never conflicts, and the
#      source list is stable enough for a three line context.
#
#   2. The per module helpers.  Each is appended to the contains part of
#      its module, and the tail of a module is where new procedures are
#      added, so a context diff of it drifts (and drifts differently on
#      develop and on the release branches, which is how the single patch
#      for both first broke).  The helpers are therefore generated here
#      from the list of affected types and inserted by pattern, anchored
#      on the 'private' statement and on 'end module'.
#
#   3. The hook in neko_init.  The use block of the master module and the
#      declarations of neko_init change with almost every new feature, so
#      the two lines are inserted by pattern instead, anchored on the last
#      use statement and on the first executable statement.
#
#   4. The build dependencies.  src/.depends is generated by 'make depend'
#      and its neko.lo entry lists every module in Neko on a single line,
#      so any new use statement anywhere in the tree invalidates a context
#      diff of it.  It is therefore edited by pattern here as well.
#
set -e

top=`dirname "$0"`/..
cd "$top"

patch_file=patches/fujitsu_memleak.patch
depends=src/.depends
workaround=src/common/fujitsu_memleak.f90

# Dependencies of the workaround module itself.  Keep in sync with the use
# statements of src/common/fujitsu_memleak.f90.
fj_deps="common/fujitsu_memleak.f90 ale/ale_rigid_kinematics.lo \
field/field_series.lo field/field.lo gs/gather_scatter.lo adt/uset.lo \
adt/stack.lo global_interpolation/cartesian_pe_finder.lo \
global_interpolation/global_interpolation_comm.lo \
multigrid/tree_amg_multigrid.lo multigrid/tree_amg.lo mesh/mesh.lo \
adt/htable.lo"

# Modules whose affected types are private, and thus need a helper of their
# own for fujitsu_memleak_workaround() to reach them.  One record per line,
# 'file module type[,type...]'.  Extend the type lists here if the leak
# persists, no other part of the script needs to know about them.
fj_helpers="\
src/adt/htable.f90 htable h_tuple_t,htable_t,htable_i4_t,htable_i8_t,htable_r8_t,htable_pt_t,htable_i4t2_t,htable_i4t4_t,htable_cptr_t
src/mesh/mesh.f90 mesh mesh_element_t,mesh_t
src/multigrid/tree_amg.f90 tree_amg tamg_node_t,tamg_lvl_t,tamg_hierarchy_t
src/multigrid/tree_amg_multigrid.f90 tree_amg_multigrid tamg_wrk_t,tamg_solver_t
src/global_interpolation/global_interpolation_comm.f90 glb_intrp_comm glb_intrp_comm_mpi_t,glb_intrp_comm_t
src/global_interpolation/cartesian_pe_finder.f90 cartesian_pe_finder i8_mpi_t,cartesian_pe_finder_t"

# Each of the four parts is guarded on its own, so that a tree left half
# patched by an interrupted or partly rejected earlier attempt is completed
# rather than reported as done.

# 1. The workaround module.  -F3 tolerates line drift, --forward turns an
#    already applied patch into a skip rather than a reversal.
if grep -q 'common/fujitsu_memleak\.f90' src/Makefile.am && [ -f "$workaround" ]
then
    echo "fujitsu_memleak: workaround module already in place, skipping"
else
    if [ -f "$workaround" ]; then
        # The file is untracked (and invisible, the repo sets
        # status.showUntrackedFiles=no), so reverting an earlier apply with
        # 'git checkout' leaves it behind, and the patch then refuses to
        # create it.  Drop it when it is the one the patch carries, and
        # keep a locally modified one rather than silently overwriting it.
        awk '/^\+\+\+ .*fujitsu_memleak\.f90/ { f = 1; next }
             f && /^(diff |--- )/ { exit }
             f && /^\+/ { sub(/^\+/, ""); print }' "$patch_file" \
            > "$workaround".fj
        if cmp -s "$workaround".fj "$workaround"; then
            rm -f "$workaround" "$workaround".fj
        else
            rm -f "$workaround".fj
            echo "fujitsu_memleak: $workaround exists and differs from the" \
                 "one in $patch_file, remove it and re-run" >&2
            exit 1
        fi
    fi
    # patch reports an already applied hunk as a failure, so check the
    # result rather than the exit status: only one of the two pieces may
    # have been missing.
    patch -p1 -F3 --forward < "$patch_file" || true
    if ! grep -q 'common/fujitsu_memleak\.f90' src/Makefile.am \
            || [ ! -f "$workaround" ]; then
        echo "fujitsu_memleak: $patch_file did not apply, see the .rej files" >&2
        exit 1
    fi
    rm -f src/Makefile.am.rej "$workaround".rej
    echo "fujitsu_memleak: workaround module applied"
fi

# 2. Per module helpers.
while read file module types; do
    if grep -q "${module}_fujitsu_memleak_workaround" "$file" 2> /dev/null; then
        # A helper left by an earlier context diff of the module tail may
        # have been misplaced: with no context left to match, patch falls
        # back to the line number recorded in the hunk, which lands in the
        # middle of whatever procedure now occupies it.  Check that the
        # helper is a peer of the other module procedures before trusting
        # it, a nested subprogram only fails much later, in the compiler.
        if awk '
        $0 ~ /^ *subroutine [a-z_]*_fujitsu_memleak_workaround/ && !seen {
            seen = 1
            ok = (last ~ /^ *end *(subroutine|function)/ ||
                  last ~ /^ *contains *$/)
            exit
        }
        /^ *$/ || /^ *!/ { next }
        { last = $0 }
        END { exit ok ? 0 : 1 }' "$file"; then
            echo "fujitsu_memleak: helper already present in $file, skipping"
            continue
        else
            echo "fujitsu_memleak: the helper in $file is missing or not at" \
                 "module scope, an earlier apply put it inside another" \
                 "procedure; run 'git checkout -- $file' and re-run" >&2
            exit 1
        fi
    fi
    awk -v module="$module" -v types="$types" '
    function helper(   n, i, t) {
        n = split(types, t, ",")
        print "  !> Workaround for a memory leak in the Fujitsu compiler runtime."
        print "  !! Nullifying a polymorphic pointer of each type materialises the type'"'"'s"
        print "  !! runtime descriptor once, preventing the runtime from re-allocating (and"
        print "  !! leaking) it on every polymorphic binding of the type. Called from"
        print "  !! fujitsu_memleak_workaround(), see common/fujitsu_memleak.f90 and"
        print "  !! https://www.fugaku.r-ccs.riken.jp/bug/20260120_01"
        print "  subroutine " module "_fujitsu_memleak_workaround()"
        for (i = 1; i <= n; i++)
            print "    class(" t[i] "), pointer :: tmp_" t[i]
        print ""
        for (i = 1; i <= n; i++)
            print "    tmp_" t[i] " => null()"
        print ""
        print "  end subroutine " module "_fujitsu_memleak_workaround"
        print ""
    }
    /^ *implicit none/ { implicit = 1 }
    # The module level private, not the component accessibility statement of
    # a derived type, hence the preceding implicit none.
    /^ *private *$/ && implicit && !declared {
        print
        print ""
        print "  public :: " module "_fujitsu_memleak_workaround"
        declared = 1
        prev = "public"
        next
    }
    /^ *end module/ && !defined {
        if (prev != "") print ""
        helper()
        defined = 1
    }
    { print; prev = $0 }
    END { exit (declared && defined) ? 0 : 1 }' "$file" > "$file".fj \
        || { echo "fujitsu_memleak: no 'private' or 'end module' statement in" \
                  "$file, add the helper by hand" >&2
             rm -f "$file".fj; exit 1; }
    mv "$file".fj "$file"
    echo "fujitsu_memleak: helper inserted in $file"
done <<EOF
$fj_helpers
EOF

# 3. Hook in neko_init.
need_use=1
need_call=1
grep -q '^ *use fujitsu_memleak' src/neko.f90 2> /dev/null && need_use=0
grep -q 'call fujitsu_memleak_workaround' src/neko.f90 2> /dev/null && need_call=0
if [ $need_use -eq 0 ] && [ $need_call -eq 0 ]; then
    echo "fujitsu_memleak: hook already present in neko_init, skipping"
else
    awk -v need_use=$need_use -v need_call=$need_call '
    /^ *use, intrinsic :: iso_fortran_env/ && need_use && !used {
        print "  use fujitsu_memleak, only : fujitsu_memleak_workaround"
        used = 1
    }
    /^ *call date_and_time/ && need_call && !called {
        print "    ! Must execute before the affected types are bound to any polymorphic"
        print "    ! entity (see common/fujitsu_memleak.f90)"
        print "    call fujitsu_memleak_workaround()"
        print ""
        called = 1
    }
    { print }
    END { if ((need_use && !used) || (need_call && !called)) exit 1 }' \
        src/neko.f90 > src/neko.f90.fj \
        || { echo "fujitsu_memleak: anchors not found in src/neko.f90, add the" \
                  "use statement and the call to neko_init by hand" >&2
             rm -f src/neko.f90.fj; exit 1; }
    mv src/neko.f90.fj src/neko.f90
    echo "fujitsu_memleak: hook inserted in neko_init"
fi

# 4. Build dependencies.
if grep -q '^common/fujitsu_memleak\.lo' "$depends" 2> /dev/null; then
    echo "fujitsu_memleak: dependencies already registered, skipping"
else
    if ! grep -q '^neko\.lo : neko\.f90' "$depends" 2> /dev/null; then
        echo "fujitsu_memleak: no neko.lo entry in $depends," \
             "run 'make depend' instead" >&2
        exit 1
    fi
    sed -e "s|^neko\.lo : neko\.f90|neko.lo : neko.f90 common/fujitsu_memleak.lo|" \
        "$depends" > "$depends".fj
    echo "common/fujitsu_memleak.lo : $fj_deps " >> "$depends".fj
    mv "$depends".fj "$depends"
    echo "fujitsu_memleak: dependencies registered in $depends"
fi
