#!/bin/sh
#
# Apply the workaround for the Fujitsu Fortran runtime memory leak
# (https://www.fugaku.r-ccs.riken.jp/bug/20260120_01).
#
# Run once from anywhere, before ./regen.sh && ./configure:
#
#     sh patches/fujitsu_memleak.sh
#
# The script is idempotent, re-running it on an already patched tree does
# nothing.  It is deliberately split in three parts, so that the churn of
# the surrounding code does not invalidate the workaround:
#
#   1. The workaround itself, carried as a context diff.  Its anchors (the
#      'private' statement of a module specification part and the closing
#      'end module') are stable, so the diff survives unrelated changes to
#      the affected files, and the same patch applies to develop and to the
#      release branches.
#
#   2. The hook in neko_init.  The use block of the master module and the
#      declarations of neko_init change with almost every new feature, so
#      the two lines are inserted by pattern instead, anchored on the last
#      use statement and on the first executable statement.
#
#   3. The build dependencies.  src/.depends is generated by 'make depend'
#      and its neko.lo entry lists every module in Neko on a single line,
#      so any new use statement anywhere in the tree invalidates a context
#      diff of it.  It is therefore edited by pattern here as well.
#
set -e

top=`dirname "$0"`/..
cd "$top"

patch_file=patches/fujitsu_memleak.patch
depends=src/.depends

# Dependencies of the workaround module itself.  Keep in sync with the use
# statements of src/common/fujitsu_memleak.f90.
fj_deps="common/fujitsu_memleak.f90 ale/ale_rigid_kinematics.lo \
field/field_series.lo field/field.lo gs/gather_scatter.lo adt/uset.lo \
adt/stack.lo global_interpolation/cartesian_pe_finder.lo \
global_interpolation/global_interpolation_comm.lo \
multigrid/tree_amg_multigrid.lo multigrid/tree_amg.lo mesh/mesh.lo \
adt/htable.lo"

# Each of the three parts is guarded on its own, so that a tree left half
# patched by an interrupted or partly rejected earlier attempt is completed
# rather than reported as done.

# 1. Source changes.  -F3 tolerates line drift, --forward turns an already
#    applied patch into a skip rather than a reversal.
if grep -q fujitsu_memleak_workaround src/adt/htable.f90 2> /dev/null; then
    echo "fujitsu_memleak: source changes already applied, skipping"
else
    if [ -f src/common/fujitsu_memleak.f90 ]; then
        echo "fujitsu_memleak: src/common/fujitsu_memleak.f90 exists but the" \
             "modules are unpatched, remove the stray file and re-run" >&2
        exit 1
    fi
    patch -p1 -F3 --forward < "$patch_file"
    echo "fujitsu_memleak: source changes applied"
fi

# 2. Hook in neko_init.
need_use=1
need_call=1
grep -q '^ *use fujitsu_memleak' src/neko.f90 2> /dev/null && need_use=0
grep -q 'call fujitsu_memleak_workaround' src/neko.f90 2> /dev/null && need_call=0
if [ $need_use -eq 0 ] && [ $need_call -eq 0 ]; then
    echo "fujitsu_memleak: hook already present in neko_init, skipping"
else
    awk -v need_use=$need_use -v need_call=$need_call '
    /^ *use, intrinsic :: iso_fortran_env/ && need_use && !used {
        print "  use fujitsu_memleak, only : fujitsu_memleak_workaround"
        used = 1
    }
    /^ *call date_and_time/ && need_call && !called {
        print "    ! Must execute before the affected types are bound to any polymorphic"
        print "    ! entity (see common/fujitsu_memleak.f90)"
        print "    call fujitsu_memleak_workaround()"
        print ""
        called = 1
    }
    { print }
    END { if ((need_use && !used) || (need_call && !called)) exit 1 }' \
        src/neko.f90 > src/neko.f90.fj \
        || { echo "fujitsu_memleak: anchors not found in src/neko.f90, add the" \
                  "use statement and the call to neko_init by hand" >&2
             rm -f src/neko.f90.fj; exit 1; }
    mv src/neko.f90.fj src/neko.f90
    echo "fujitsu_memleak: hook inserted in neko_init"
fi

# 3. Build dependencies.
if grep -q '^common/fujitsu_memleak\.lo' "$depends" 2> /dev/null; then
    echo "fujitsu_memleak: dependencies already registered, skipping"
else
    if ! grep -q '^neko\.lo : neko\.f90' "$depends" 2> /dev/null; then
        echo "fujitsu_memleak: no neko.lo entry in $depends," \
             "run 'make depend' instead" >&2
        exit 1
    fi
    sed -e "s|^neko\.lo : neko\.f90|neko.lo : neko.f90 common/fujitsu_memleak.lo|" \
        "$depends" > "$depends".fj
    echo "common/fujitsu_memleak.lo : $fj_deps " >> "$depends".fj
    mv "$depends".fj "$depends"
    echo "fujitsu_memleak: dependencies registered in $depends"
fi
