const char *mapping_kernels =
"#ifndef __SOURCE_TERMS_MAPPING_KERNELS__\n"
"#define __SOURCE_TERMS_MAPPING_KERNELS__\n"
"/*\n"
" Copyright (c) 2021-2024, The Neko Authors\n"
" All rights reserved.\n"
"\n"
" Redistribution and use in source and binary forms, with or without\n"
" modification, are permitted provided that the following conditions\n"
" are met:\n"
"\n"
"   * Redistributions of source code must retain the above copyright\n"
"     notice, this list of conditions and the following disclaimer.\n"
"\n"
"   * Redistributions in binary form must reproduce the above\n"
"     copyright notice, this list of conditions and the following\n"
"     disclaimer in the documentation and/or other materials provided\n"
"     with the distribution.\n"
"\n"
"   * Neither the name of the authors nor the names of its\n"
"     contributors may be used to endorse or promote products derived\n"
"     from this software without specific prior written permission.\n"
"\n"
" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
" \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n"
" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n"
" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n"
" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
" POSSIBILITY OF SUCH DAMAGE.\n"
"*/\n"
"\n"
"/**\n"
" * Device kernel for smooth step function.\n"
" *\n"
" * @param x  in/out array\n"
" * @param edge0  lower edge\n"
" * @param edge1  upper edge\n"
" * @param n  size of the input array\n"
" */\n"
"__kernel void smooth_step_kernel(\n"
"    __global double* __restrict__ x, const real edge0, const real edge1,\n"
"    const int n) {\n"
"\n"
"    const int idx = get_global_id(0);\n"
"    const int str = get_global_size(0);\n"
"\n"
"    for (int i = idx; i < n; i += str) {\n"
"        double t = (x[i] - edge0) / (edge1 - edge0);\n"
"        t      = min(max(t, 0.0), 1.0);\n"
"        x[i]   = pow(t, 3.0) * (t * (t * 6.0 - 15.0) + 10.0);\n"
"    }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for step function.\n"
" *\n"
" * @param x  input array\n"
" * @param edge  step location\n"
" * @param left  value to the left of the step\n"
" * @param right  value to the right of the step\n"
" * @param n  size of the input array\n"
" */\n"
"__kernel void step_kernel(\n"
"    __global double* __restrict__ x, const real edge, const real left,\n"
"    const double right, const int n) {\n"
"\n"
"    const int idx = get_global_id(0);\n"
"    const int str = get_global_size(0);\n"
"\n"
"    for (int i = idx; i < n; i += str) {\n"
"        const double x_i = x[i];\n"
"        x[i]           = (x_i < edge) ? left : right;\n"
"    }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for the inverse permeability kernel.\n"
" *\n"
" * @param x  input array\n"
" * @param k_0  lower bound of the permeability\n"
" * @param k_1  upper bound of the permeability\n"
" * @param q  parameter\n"
" * @param n  size of the input array\n"
" */\n"
"__kernel void permeability_kernel(\n"
"    __global double* __restrict__ x, const real k_0, const real k_1, const real q,\n"
"    const int n) {\n"
"\n"
"    const int idx = get_global_id(0);\n"
"    const int str = get_global_size(0);\n"
"\n"
"    for (int i = idx; i < n; i += str) {\n"
"        const double x_i = x[i];\n"
"        x[i]           = k_0 + (k_1 - k_0) * x_i * (q + 1.0) / (q + x_i);\n"
"    }\n"
"}\n"
"\n"
"#endif /* __SOURCE_TERMS_MAPPING_KERNELS__ */\n";
