
image: debian:testing


pipelines:
  pull-requests:
   '**':
    - parallel:
        - step:
            name: Build
            script:
              - apt-get update
              - apt-get install -y --no-install-recommends gfortran autoconf automake autotools-dev libmpich-dev mpich cmake libopenblas-dev make git m4 python3 ca-certificates
              - update-alternatives --install /usr/bin/python python /usr/bin/python3 2
              - git clone https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git && cd pFUnit && mkdir b && cd b && cmake -DCMAKE_INSTALL_PREFIX=/opt/pfunit .. && make -j 4 && make install && cd ../../
              - ./regen.sh
              - ./configure --with-pfunit=/opt/pfunit/PFUNIT-4.2
              - make -j 4
              - make check
              - make dist
              - tar xf neko-0.0.1.tar.gz
              - cd neko-0.0.1
              - ./configure FC=${FC}
              - make -j 4
