const char *compute_max_wave_speed_kernel =
"/*\n"
" Copyright (c) 2025, The Neko Authors\n"
" All rights reserved.\n"
"\n"
" Redistribution and use in source and binary forms, with or without\n"
" modification, are permitted provided that the following conditions\n"
" are met:\n"
"\n"
"   * Redistributions of source code must retain the above copyright\n"
"     notice, this list of conditions and the following disclaimer.\n"
"\n"
"   * Redistributions in binary form must reproduce the above\n"
"     copyright notice, this list of conditions and the following\n"
"     disclaimer in the documentation and/or other materials provided\n"
"     with the distribution.\n"
"\n"
"   * Neither the name of the authors nor the names of its\n"
"     contributors may be used to endorse or promote products derived\n"
"     from this software without specific prior written permission.\n"
"\n"
" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
" \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n"
" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n"
" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n"
" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
" POSSIBILITY OF SUCH DAMAGE.\n"
"*/\n"
"\n"
"#ifndef __OPENCL_COMPUTE_MAX_WAVE_SPEED_KERNEL__\n"
"#define __OPENCL_COMPUTE_MAX_WAVE_SPEED_KERNEL__\n"
"\n"
"/**\n"
" * Device kernel for compute_max_wave_speed\n"
" */\n"
"__kernel void compute_max_wave_speed_kernel(__global double * max_wave_speed,\n"
"                                            __global const double * u,\n"
"                                            __global const double * v,\n"
"                                            __global const double * w,\n"
"                                            const double gamma,\n"
"                                            __global const double * p,\n"
"                                            __global const double * rho,\n"
"                                            const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    if (i < n) {\n"
"      double u_sq = u[i] * u[i];\n"
"      double v_sq = v[i] * v[i]; \n"
"      double w_sq = w[i] * w[i];\n"
"      double vel_mag = sqrt(u_sq + v_sq + w_sq);\n"
"      double sound_speed = sqrt(gamma * p[i] / rho[i]);\n"
"      max_wave_speed[i] = vel_mag + sound_speed;\n"
"    }\n"
"  }\n"
"\n"
"}\n"
"\n"
"#endif // __OPENCL_COMPUTE_MAX_WAVE_SPEED_KERNEL__ \n";
