const char *fdm_kernel =
"#ifndef __MATH_FDM_KERNEL_CL__\n"
"#define __MATH_FDM_KERNEL_CL__\n"
"/*\n"
" Copyright (c) 2022, The Neko Authors\n"
" All rights reserved.\n"
"\n"
" Redistribution and use in source and binary forms, with or without\n"
" modification, are permitted provided that the following conditions\n"
" are met:\n"
"\n"
"   * Redistributions of source code must retain the above copyright\n"
"     notice, this list of conditions and the following disclaimer.\n"
"\n"
"   * Redistributions in binary form must reproduce the above\n"
"     copyright notice, this list of conditions and the following\n"
"     disclaimer in the documentation and/or other materials provided\n"
"     with the distribution.\n"
"\n"
"   * Neither the name of the authors nor the names of its\n"
"     contributors may be used to endorse or promote products derived\n"
"     from this software without specific prior written permission.\n"
"\n"
" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
" \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n"
" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n"
" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n"
" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
" POSSIBILITY OF SUCH DAMAGE.\n"
"*/\n"
"\n"
"#define DEFINE_FDM_DO_FAST_KERNEL(NL)                                          \\\n"
"__kernel void fdm_do_fast_kernel_nl##NL(__global double * __restrict__ e,        \\\n"
"                                        __global double * __restrict__ r,        \\\n"
"                                        __global double * __restrict__ s,        \\\n"
"                                        __global double * __restrict__ d) {      \\\n"
"                                                                               \\\n"
"  __local double shwork[NL*NL*NL];                                               \\\n"
"  __local double shwork2[NL*NL*NL];                                              \\\n"
"  __local double A[NL*NL];                                                       \\\n"
"  __local double Bt[NL*NL];                                                      \\\n"
"  __local double Ct[NL*NL];                                                      \\\n"
"                                                                               \\\n"
"  const int idx = get_local_id(0);                                             \\\n"
"  const int str = get_local_size(0);                                           \\\n"
"  const int el = get_group_id(0);                                              \\\n"
"  if( idx < NL*NL){                                                            \\\n"
"     A[idx] = s[idx+NL*NL+el*NL*NL*3*2];                                       \\\n"
"    Bt[idx] = s[idx+2*NL*NL+el*NL*NL*3*2];                                     \\\n"
"    Ct[idx] = s[idx+2*2*NL*NL+el*NL*NL*3*2];                                   \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int ii = idx; ii< NL*NL*NL; ii += str){                                 \\\n"
"    double tmp = 0.0;                                                            \\\n"
"    int j = ii/NL;                                                             \\\n"
"    int i = ii - j*NL;                                                         \\\n"
"    for( int l = 0; l < NL; l++){                                              \\\n"
"      tmp += A[i+l*NL]*r[l+NL*j+el*NL*NL*NL];                                  \\\n"
"    }                                                                          \\\n"
"    shwork[ii] = tmp;                                                          \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int ijk = idx; ijk< NL*NL*NL; ijk += str){                              \\\n"
"    const int jk = ijk / NL;                                                   \\\n"
"    const int i = ijk - jk * NL;                                               \\\n"
"    const int k = jk / NL;                                                     \\\n"
"    const int j = jk - k * NL;                                                 \\\n"
"    double tmp = 0.0;                                                            \\\n"
"    const int ik2 = i + k*NL*NL;                                               \\\n"
"    for( int l = 0; l < NL; l++){                                              \\\n"
"      tmp += Bt[l+j*NL]*shwork[l*NL+ik2];                                      \\\n"
"    }                                                                          \\\n"
"    shwork2[ijk] = tmp;                                                        \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int ijk = idx; ijk< NL*NL*NL; ijk += str){                              \\\n"
"    const int jk = ijk / NL;                                                   \\\n"
"    const int i = ijk - jk * NL;                                               \\\n"
"    const int k = jk / NL;                                                     \\\n"
"    const int j = jk - k * NL;                                                 \\\n"
"    double tmp = 0.0;                                                            \\\n"
"    const int ij2 = i + j*NL;                                                  \\\n"
"    for( int l = 0; l < NL; l++){                                              \\\n"
"      tmp += Ct[l+k*NL]*shwork2[ij2 + l*NL*NL];                                \\\n"
"    }                                                                          \\\n"
"    r[ijk+el*NL*NL*NL] = tmp*d[ijk+el*NL*NL*NL];                               \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  if( idx < NL*NL){                                                            \\\n"
"     A[idx] = s[idx+el*NL*NL*3*2];                                             \\\n"
"    Bt[idx] = s[idx+NL*NL+2*NL*NL+el*NL*NL*3*2];                               \\\n"
"    Ct[idx] = s[idx+NL*NL+2*2*NL*NL+el*NL*NL*3*2];                             \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int ii = idx; ii< NL*NL*NL; ii += str){                                 \\\n"
"    double tmp = 0.0;                                                            \\\n"
"    int j = ii/NL;                                                             \\\n"
"    int i = ii - j*NL;                                                         \\\n"
"    for( int l = 0; l < NL; l++){                                              \\\n"
"      tmp += A[i+l*NL]*r[l+NL*j+el*NL*NL*NL];                                  \\\n"
"    }                                                                          \\\n"
"    shwork[ii] = tmp;                                                          \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int ijk = idx; ijk< NL*NL*NL; ijk += str){                              \\\n"
"    const int jk = ijk / NL;                                                   \\\n"
"    const int i = ijk - jk * NL;                                               \\\n"
"    const int k = jk / NL;                                                     \\\n"
"    const int j = jk - k * NL;                                                 \\\n"
"    double tmp = 0.0;                                                            \\\n"
"    const int ik2 = i + k*NL*NL;                                               \\\n"
"    for( int l = 0; l < NL; l++){                                              \\\n"
"      tmp += Bt[l+j*NL]*shwork[l*NL+ik2];                                      \\\n"
"    }                                                                          \\\n"
"    shwork2[ijk] = tmp;                                                        \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int ijk = idx; ijk< NL*NL*NL; ijk += str){                              \\\n"
"    const int jk = ijk / NL;                                                   \\\n"
"    const int i = ijk - jk * NL;                                               \\\n"
"    const int k = jk / NL;                                                     \\\n"
"    const int j = jk - k * NL;                                                 \\\n"
"    double tmp = 0.0;                                                            \\\n"
"    const int ij2 = i + j*NL;                                                  \\\n"
"    for( int l = 0; l < NL; l++){                                              \\\n"
"      tmp += Ct[l+k*NL]*shwork2[ij2 + l*NL*NL];                                \\\n"
"    }                                                                          \\\n"
"    e[ijk+el*NL*NL*NL] = tmp;                                                  \\\n"
"  }                                                                            \\\n"
"}\n"
"\n"
"DEFINE_FDM_DO_FAST_KERNEL(2)\n"
"DEFINE_FDM_DO_FAST_KERNEL(3)\n"
"DEFINE_FDM_DO_FAST_KERNEL(4)\n"
"DEFINE_FDM_DO_FAST_KERNEL(5)\n"
"DEFINE_FDM_DO_FAST_KERNEL(6)\n"
"DEFINE_FDM_DO_FAST_KERNEL(7)\n"
"DEFINE_FDM_DO_FAST_KERNEL(8)\n"
"DEFINE_FDM_DO_FAST_KERNEL(9)\n"
"DEFINE_FDM_DO_FAST_KERNEL(10)\n"
"DEFINE_FDM_DO_FAST_KERNEL(11)\n"
"DEFINE_FDM_DO_FAST_KERNEL(12)\n"
"DEFINE_FDM_DO_FAST_KERNEL(13)\n"
"DEFINE_FDM_DO_FAST_KERNEL(14)\n"
"DEFINE_FDM_DO_FAST_KERNEL(15)\n"
"\n"
"\n"
"#endif // __MATH_FDM_KERNEL_CL__\n"
;
