const char *mathops_kernel =
"#ifndef __MATH_MATHOPS_KERNEL_CL__\n"
"#define __MATH_MATHOPS_KERNEL_CL__\n"
"/*\n"
" Copyright (c) 2021-2022, The Neko Authors\n"
" All rights reserved.\n"
"\n"
" Redistribution and use in source and binary forms, with or without\n"
" modification, are permitted provided that the following conditions\n"
" are met:\n"
"\n"
"   * Redistributions of source code must retain the above copyright\n"
"     notice, this list of conditions and the following disclaimer.\n"
"\n"
"   * Redistributions in binary form must reproduce the above\n"
"     copyright notice, this list of conditions and the following\n"
"     disclaimer in the documentation and/or other materials provided\n"
"     with the distribution.\n"
"\n"
"   * Neither the name of the authors nor the names of its\n"
"     contributors may be used to endorse or promote products derived\n"
"     from this software without specific prior written permission.\n"
"\n"
" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
" \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n"
" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n"
" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n"
" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
" POSSIBILITY OF SUCH DAMAGE.\n"
"*/\n"
"\n"
"/**\n"
" * Device kernel for opchsign\n"
" */\n"
"__kernel void opchsign_kernel(__global double *a1, \n"
"			      __global double *a2, \n"
"			      __global double *a3,\n"
"			      const int gdim,\n"
"			      const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  if (gdim == 3) {\n"
"    for (int i = idx; i < n; i += str) {\n"
"      a1[i] = -a1[i];\n"
"      a2[i] = -a2[i];\n"
"      a3[i] = -a3[i];\n"
"    }\n"
"  } \n"
"  else {\n"
"    for (int i = idx; i < n; i += str) {\n"
"      a1[i] = -a1[i];\n"
"      a2[i] = -a2[i];\n"
"    }\n"
"  }\n"
"\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for opcolv\n"
" */\n"
"__kernel void opcolv_kernel(__global double *a1, \n"
"			    __global double *a2, \n"
"			    __global double *a3,\n"
"			    __global const double *c,\n"
"			    const int gdim,\n"
"			    const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  if (gdim == 3) {\n"
"    for (int i = idx; i < n; i += str) {\n"
"      a1[i] = a1[i] * c[i];\n"
"      a2[i] = a2[i] * c[i];\n"
"      a3[i] = a3[i] * c[i];\n"
"    }\n"
"  } \n"
"  else {\n"
"    for (int i = idx; i < n; i += str) {\n"
"      a1[i] = a1[i] * c[i];\n"
"      a2[i] = a2[i] * c[i];\n"
"    }\n"
"  }\n"
"\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for opcolv3c\n"
" */\n"
"__kernel void opcolv3c_kernel(__global double *a1, \n"
"			      __global double *a2, \n"
"			      __global double *a3,\n"
"			      __global const double *b1, \n"
"			      __global const double *b2, \n"
"			      __global const double *b3,\n"
"			      __global const double *c,\n"
"			      const double d,\n"
"			      const int gdim,\n"
"			      const int n) {\n"
"  \n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  if (gdim == 3) {\n"
"    for (int i = idx; i < n; i += str) {\n"
"      a1[i] = b1[i] * c[i] * d;\n"
"      a2[i] = b2[i] * c[i] * d;\n"
"      a3[i] = b3[i] * c[i] * d;\n"
"    }\n"
"  } \n"
"  else {\n"
"    for (int i = idx; i < n; i += str) {\n"
"      a1[i] = b1[i] * c[i] * d;\n"
"      a2[i] = b2[i] * c[i] * d;\n"
"    }\n"
"  }\n"
"\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for opadd2cm\n"
" */\n"
"__kernel void opadd2cm_kernel(__global double *a1, \n"
"			      __global double *a2, \n"
"			      __global double *a3,\n"
"			      __global const double *b1, \n"
"			      __global const double *b2, \n"
"			      __global const double *b3,\n"
"			      const double c,\n"
"			      const int gdim,\n"
"			      const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"  \n"
"  if (gdim == 3) {\n"
"    for (int i = idx; i < n; i += str) {\n"
"      a1[i] = a1[i] + b1[i] * c;\n"
"      a2[i] = a2[i] + b2[i] * c;\n"
"      a3[i] = a3[i] + b3[i] * c;\n"
"    }\n"
"  } \n"
"  else {\n"
"    for (int i = idx; i < n; i += str) {\n"
"      a1[i] = a1[i] + b1[i] * c;\n"
"      a2[i] = a2[i] + b2[i] * c;\n"
"    }\n"
"  }\n"
"\n"
"}\n"
"\n"
"\n"
"/**\n"
" * Device kernel for opadd2col\n"
" */\n"
"__kernel void opadd2col_kernel(__global double *a1, \n"
"			       __global double *a2, \n"
"			       __global double *a3,\n"
"			       __global const double *b1, \n"
"			       __global const double *b2, \n"
"			       __global const double *b3,\n"
"			       __global const double *c,\n"
"			       const int gdim,\n"
"			       const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"  \n"
"  if (gdim == 3) {\n"
"    for (int i = idx; i < n; i += str) {\n"
"      a1[i] = a1[i] + b1[i] * c[i];\n"
"      a2[i] = a2[i] + b2[i] * c[i];\n"
"      a3[i] = a3[i] + b3[i] * c[i];\n"
"    }\n"
"  } \n"
"  else {\n"
"    for (int i = idx; i < n; i += str) {\n"
"      a1[i] = a1[i] + b1[i] * c[i];\n"
"      a2[i] = a2[i] + b2[i] * c[i];\n"
"    }\n"
"  }\n"
"\n"
"}\n"
"\n"
"\n"
"#endif // __MATH_MATHOPS_KERNEL_CL__\n"
;
