const char *math_kernel =
"#ifndef __MATH_MATH_KERNEL_CL__\n"
"#define __MATH_MATH_KERNEL_CL__\n"
"/*\n"
" Copyright (c) 2021-2024, The Neko Authors\n"
" All rights reserved.\n"
"\n"
" Redistribution and use in source and binary forms, with or without\n"
" modification, are permitted provided that the following conditions\n"
" are met:\n"
"\n"
"   * Redistributions of source code must retain the above copyright\n"
"     notice, this list of conditions and the following disclaimer.\n"
"\n"
"   * Redistributions in binary form must reproduce the above\n"
"     copyright notice, this list of conditions and the following\n"
"     disclaimer in the documentation and/or other materials provided\n"
"     with the distribution.\n"
"\n"
"   * Neither the name of the authors nor the names of its\n"
"     contributors may be used to endorse or promote products derived\n"
"     from this software without specific prior written permission.\n"
"\n"
" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
" \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n"
" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n"
" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n"
" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
" POSSIBILITY OF SUCH DAMAGE.\n"
"*/\n"
"\n"
"/**\n"
" * Device kernel for masked copy\n"
" */\n"
"__kernel void masked_copy_kernel(__global double * __restrict__ a,\n"
"                                 __global double * __restrict__ b,\n"
"                                 __global int * __restrict__ mask,\n"
"                                 const int n,\n"
"                                 const int n_mask) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n_mask; i += str) {\n"
"    a[mask[i+1]-1] = b[mask[i+1]-1];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for masked gather copy\n"
" */\n"
"__kernel void masked_gather_copy_kernel(__global double * __restrict__ a,\n"
"                                     __global double * __restrict__ b,\n"
"                                     __global int * __restrict__ mask,\n"
"                                     const int n,\n"
"                                     const int n_mask) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n_mask; i += str) {\n"
"    a[i] = b[mask[i+1]-1];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for masked scatter copy\n"
" */\n"
"__kernel void masked_scatter_copy_kernel(__global double * __restrict__ a,\n"
"                                         __global double * __restrict__ b,\n"
"                                         __global int * __restrict__ mask,\n"
"                                         const int n,\n"
"                                         const int n_mask) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n_mask; i += str) {\n"
"    a[mask[i+1]-1] = b[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for cfill_mask\n"
" */\n"
"__kernel void cfill_mask_kernel(__global double * __restrict__ a,\n"
"                                const double c,\n"
"                                const int n,\n"
"                                __global int * __restrict__ mask,\n"
"                                const int n_mask) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"    for (int i = idx; i < n_mask; i += str) { a[mask[i]-1] = c; }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for cmult\n"
" */\n"
"__kernel void cmult_kernel(__global double * __restrict__ a,\n"
"                           const double c,\n"
"                           const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = c * a[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for cmult2\n"
" */\n"
"__kernel void cmult2_kernel(__global double * __restrict__ a,\n"
"               __global double * __restrict__ b,\n"
"                           const double c,\n"
"                           const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = c * b[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for cdiv\n"
" */\n"
"__kernel void cdiv_kernel(__global double * __restrict__ a,\n"
"                           const double c,\n"
"                           const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = c / a[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for cdiv2\n"
" */\n"
"__kernel void cdiv2_kernel(__global double * __restrict__ a,\n"
"               __global double * __restrict__ b,\n"
"                           const double c,\n"
"                           const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = c / b[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for cadd\n"
" */\n"
"__kernel void cadd_kernel(__global double * __restrict__ a,\n"
"                          const double c,\n"
"                          const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = a[i] + c;\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for cadd2\n"
" */\n"
"__kernel void cadd2_kernel(__global double * __restrict__ a,\n"
"                          __global const double * __restrict__ b,\n"
"                          const double c,\n"
"                          const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = b[i] + c;\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for cfill\n"
" */\n"
"__kernel void cfill_kernel(__global double * __restrict__ a,\n"
"                           const double c,\n"
"                           const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = c;\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for add4\n"
" */\n"
"__kernel void add4_kernel(__global double * __restrict__ a,\n"
"                          __global const double * __restrict__ b,\n"
"                          __global const double * __restrict__ c,\n"
"                          __global const double * __restrict__ d,\n"
"                          const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = d[i] + c[i] + d[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for add2\n"
" */\n"
"__kernel void add2_kernel(__global double * __restrict__ a,\n"
"                          __global const double * __restrict__ b,\n"
"                          const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = a[i] + b[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for add3\n"
" */\n"
"__kernel void add3_kernel(__global double * __restrict__ a,\n"
"                          __global const double * __restrict__ b,\n"
"                          __global const double * __restrict__ c,\n"
"                          const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = b[i] + c[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for add2s1\n"
" */\n"
"__kernel void add2s1_kernel(__global double * __restrict__ a,\n"
"                            __global const double * __restrict__ b,\n"
"                            const double c1,\n"
"                            const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = c1 * a[i] + b[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for add2s2\n"
" */\n"
"__kernel void add2s2_kernel(__global double * __restrict__ a,\n"
"                            __global const double * __restrict__ b,\n"
"                            const double c1,\n"
"                            const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = a[i] + c1 * b[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for add2s2 many\n"
" */\n"
"__kernel void add2s2_many_kernel(__global  double * __restrict__  x,\n"
"                                 __global const double * __restrict__  p,\n"
"                                 __global const double * __restrict__ alpha,\n"
"                                 const int p_cur,\n"
"                                 const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_local_size(0) * get_num_groups(0);\n"
"\n"
"  for (int i = idx; i < n; i+= str) {\n"
"    double tmp = 0.0;\n"
"    for (int j = 0; j < p_cur; j ++) {\n"
"      tmp += p[j * n + i]*alpha[j];\n"
"    }\n"
"    x[i] += tmp;\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for addsqr2s2\n"
" */\n"
"__kernel void addsqr2s2_kernel(__global double * __restrict__ a,\n"
"                               __global const double * __restrict__ b,\n"
"                               const double c1,\n"
"                               const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = a[i] + c1 * (b[i] * b[i]);\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for add3s2\n"
" */\n"
"__kernel void add3s2_kernel(__global double * __restrict__ a,\n"
"                            __global const double * __restrict__ b,\n"
"                            __global const double * __restrict__ c,\n"
"                            const double c1,\n"
"                            const double c2,\n"
"                            const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = c1 * b[i] + c2 * c[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for add4s3\n"
" */\n"
"__kernel void add4s3_kernel(__global double * __restrict__ a,\n"
"                            __global const double * __restrict__ b,\n"
"                            __global const double * __restrict__ c,\n"
"                            __global const double * __restrict__ d,\n"
"                            const double c1,\n"
"                            const double c2,\n"
"                            const double c3,\n"
"                            const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = c1 * b[i] + c2 * c[i] + c3 * d[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for add5s4\n"
" */\n"
"__kernel void add5s4_kernel(__global double * __restrict__ a,\n"
"                            __global const double * __restrict__ b,\n"
"                            __global const double * __restrict__ c,\n"
"                            __global const double * __restrict__ d,\n"
"                            __global const double * __restrict__ e,\n"
"                            const double c1,\n"
"                            const double c2,\n"
"                            const double c3,\n"
"                            const double c4,\n"
"                            const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = a[i] + c1 * b[i] + c2 * c[i] + c3 * d[i] + c4 * e[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for invcol1\n"
" */\n"
"__kernel void invcol1_kernel(__global double * __restrict__ a,\n"
"                             const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"  const double one = 1.0;\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = one / a[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for invcol2\n"
" */\n"
"__kernel void invcol2_kernel(__global double * __restrict__ a,\n"
"                             __global const double * __restrict__ b,\n"
"                             const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = a[i] / b[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for col2\n"
" */\n"
"__kernel void col2_kernel(__global double * __restrict__ a,\n"
"                          __global const double * __restrict__ b,\n"
"                          const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = a[i] * b[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for col3\n"
" */\n"
"__kernel void col3_kernel(__global double * __restrict__ a,\n"
"                          __global const double * __restrict__ b,\n"
"                          __global const double * __restrict__ c,\n"
"                          const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = b[i] * c[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for subcol3\n"
" */\n"
"__kernel void subcol3_kernel(__global double * __restrict__ a,\n"
"                             __global const double * __restrict__ b,\n"
"                             __global const double * __restrict__ c,\n"
"                             const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = a[i] - b[i] * c[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for sub2\n"
" */\n"
"__kernel void sub2_kernel(__global double * __restrict__ a,\n"
"                          __global const double * __restrict__ b,\n"
"                          const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = a[i] - b[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for sub3\n"
" */\n"
"__kernel void sub3_kernel(__global double * __restrict__ a,\n"
"                          __global const double * __restrict__ b,\n"
"                          __global const double * __restrict__ c,\n"
"                          const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = b[i] - c[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for addcol3\n"
" */\n"
"__kernel void addcol3_kernel(__global double * __restrict__ a,\n"
"                             __global const double * __restrict__ b,\n"
"                             __global const double * __restrict__ c,\n"
"                             const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = a[i] + b[i] * c[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for addcol4\n"
" */\n"
"__kernel void addcol4_kernel(__global double * __restrict__ a,\n"
"                             __global const double * __restrict__ b,\n"
"                             __global const double * __restrict__ c,\n"
"                             __global const double * __restrict__ d,\n"
"                             const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = a[i] + b[i] * c[i] * d[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for addcol3s2\n"
" */\n"
"__kernel void addcol3s2_kernel(__global double * __restrict__ a,\n"
"                               __global const double * __restrict__ b,\n"
"                               __global const double * __restrict__ c,\n"
"                               const double s,\n"
"                               const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    a[i] = a[i] + s * b[i] * c[i];\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for vdot3\n"
" */\n"
"__kernel void vdot3_kernel(__global double * __restrict__ dot,\n"
"                           __global const double * __restrict__ u1,\n"
"                           __global const double * __restrict__ u2,\n"
"                           __global const double * __restrict__ u3,\n"
"                           __global const double * __restrict__ v1,\n"
"                           __global const double * __restrict__ v2,\n"
"                           __global const double * __restrict__ v3,\n"
"                           const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    dot[i] = u1[i] * v1[i]  + u2[i] * v2[i] + u3[i] * v3[i];\n"
"  }\n"
"\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for vcross\n"
" */\n"
"__kernel void vcross_kernel(__global double * __restrict__ u1,\n"
"                            __global double * __restrict__ u2,\n"
"                            __global double * __restrict__ u3,\n"
"                            __global const double * __restrict__ v1,\n"
"                            __global const double * __restrict__ v2,\n"
"                            __global const double * __restrict__ v3,\n"
"                            __global const double * __restrict__ w1,\n"
"                            __global const double * __restrict__ w2,\n"
"                            __global const double * __restrict__ w3,\n"
"                            const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    u1[i] = v2[i]*w3[i] - v3[i]*w2[i];\n"
"    u2[i] = v3[i]*w1[i] - v1[i]*w3[i];\n"
"    u3[i] = v1[i]*w2[i] - v2[i]*w1[i];\n"
"  }\n"
"\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for glsc3\n"
" */\n"
"__kernel void glsc3_kernel(__global const double * __restrict__ a,\n"
"                           __global const double * __restrict__ b,\n"
"                           __global const double * __restrict__ c,\n"
"                           __global double * __restrict__ buf_h,\n"
"                           const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  __local double buf[256]; /* Make this nice...*/\n"
"  double tmp = 0.0;\n"
"\n"
"  for (int i = idx; i < n; i+= str) {\n"
"    tmp += a[i] * b[i] * c[i];\n"
"  }\n"
"  buf[get_local_id(0)] = tmp;\n"
"  barrier(CLK_LOCAL_MEM_FENCE);\n"
"\n"
"  int i = (get_local_size(0))>>1;\n"
"  while (i != 0) {\n"
"    if (get_local_id(0) < i) {\n"
"      buf[get_local_id(0)] += buf[get_local_id(0) + i];\n"
"    }\n"
"    barrier(CLK_LOCAL_MEM_FENCE);\n"
"    i = i>>1;\n"
"  }\n"
"\n"
"  if (get_local_id(0) == 0) {\n"
"    buf_h[get_group_id(0)] = buf[0];\n"
"  }\n"
"\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for glsc3 many\n"
" */\n"
"__kernel void glsc3_many_kernel(__global const double * __restrict__ a,\n"
"                                __global const double * __restrict__ b,\n"
"                                __global const double * __restrict__ c,\n"
"                                __global double * __restrict__ buf_h,\n"
"                                const int j,\n"
"                                const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"  const int y = get_local_id(1);\n"
"\n"
"  __local double buf[256]; /* Make this nice...*/\n"
"  double tmp = 0;\n"
"  if(y < j){\n"
"    for (int i = idx; i < n; i+= str) {\n"
"      tmp += a[i] * b[get_local_id(1) * n + i] * c[i];\n"
"    }\n"
"  }\n"
"\n"
"  buf[get_local_id(0) * get_local_size(1) + y] = tmp;\n"
"  barrier(CLK_LOCAL_MEM_FENCE);\n"
"\n"
"  int i = get_local_size(0)>>1;\n"
"  while (i != 0) {\n"
"    if (get_local_id(0) < i) {\n"
"      buf[get_local_id(0) * get_local_size(1) + y] +=\n"
"        buf[(get_local_id(0) + i) * get_local_size(1) + y];\n"
"    }\n"
"    barrier(CLK_LOCAL_MEM_FENCE);\n"
"    i = i>>1;\n"
"  }\n"
"\n"
"  if (get_local_id(0) == 0) {\n"
"    if( y < j) {\n"
"      buf_h[j * get_group_id(0) + y] = buf[y];\n"
"    }\n"
"  }\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for glsc2\n"
" */\n"
"__kernel void glsc2_kernel(__global const double * __restrict__ a,\n"
"                           __global const double * __restrict__ b,\n"
"                           __global double * __restrict__ buf_h,\n"
"                           const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  __local double buf[256]; /* Make this nice...*/\n"
"  double tmp = 0.0;\n"
"\n"
"  for (int i = idx; i < n; i+= str) {\n"
"    tmp += a[i] * b[i];\n"
"  }\n"
"  buf[get_local_id(0)] = tmp;\n"
"  barrier(CLK_LOCAL_MEM_FENCE);\n"
"\n"
"  int i = (get_local_size(0))>>1;\n"
"  while (i != 0) {\n"
"    if (get_local_id(0) < i) {\n"
"      buf[get_local_id(0)] += buf[get_local_id(0) + i];\n"
"    }\n"
"    barrier(CLK_LOCAL_MEM_FENCE);\n"
"    i = i>>1;\n"
"  }\n"
"\n"
"  if (get_local_id(0) == 0) {\n"
"    buf_h[get_group_id(0)] = buf[0];\n"
"  }\n"
"\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for glsubnorm2\n"
" */\n"
"__kernel void glsubnorm2_kernel(__global const double * __restrict__ a,\n"
"                                __global const double * __restrict__ b,\n"
"                                __global double * __restrict__ buf_h,\n"
"                                const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  __local double buf[256]; /* Make this nice...*/\n"
"  double tmp = 0.0;\n"
"\n"
"  for (int i = idx; i < n; i+= str) {\n"
"    tmp += pow(a[i] - b[i], (double) 2.0);\n"
"  }\n"
"  buf[get_local_id(0)] = tmp;\n"
"  barrier(CLK_LOCAL_MEM_FENCE);\n"
"\n"
"  int i = (get_local_size(0))>>1;\n"
"  while (i != 0) {\n"
"    if (get_local_id(0) < i) {\n"
"      buf[get_local_id(0)] += buf[get_local_id(0) + i];\n"
"    }\n"
"    barrier(CLK_LOCAL_MEM_FENCE);\n"
"    i = i>>1;\n"
"  }\n"
"\n"
"  if (get_local_id(0) == 0) {\n"
"    buf_h[get_group_id(0)] = buf[0];\n"
"  }\n"
"\n"
"}\n"
"\n"
"/**\n"
" * Device kernel for glsum\n"
" */\n"
"__kernel void glsum_kernel(__global const double * __restrict__ a,\n"
"			   __global double * __restrict__ buf_h,\n"
"                           const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  __local double buf[256]; /* Make this nice...*/\n"
"  double tmp = 0.0;\n"
"\n"
"  for (int i = idx; i < n; i+= str) {\n"
"    tmp += a[i];\n"
"  }\n"
"  buf[get_local_id(0)] = tmp;\n"
"  barrier(CLK_LOCAL_MEM_FENCE);\n"
"\n"
"  int i = (get_local_size(0))>>1;\n"
"  while (i != 0) {\n"
"    if (get_local_id(0) < i) {\n"
"      buf[get_local_id(0)] += buf[get_local_id(0) + i];\n"
"    }\n"
"    barrier(CLK_LOCAL_MEM_FENCE);\n"
"    i = i>>1;\n"
"  }\n"
"\n"
"  if (get_local_id(0) == 0) {\n"
"    buf_h[get_group_id(0)] = buf[0];\n"
"  }\n"
"\n"
"}\n"
"\n"
"#endif // __MATH_MATH_KERNEL_CL__\n"
;
