const char *set_convect_rst_kernel =
"#ifndef __MATH_SET_CONVECT_RST_KERNEL_CL__\n"
"#define __MATH_SET_CONVECT_RST_KERNEL_CL__\n"
"/*\n"
" Copyright (c) 2021-2022, The Neko Authors\n"
" All rights reserved.\n"
"\n"
" Redistribution and use in source and binary forms, with or without\n"
" modification, are permitted provided that the following conditions\n"
" are met:\n"
"\n"
"   * Redistributions of source code must retain the above copyright\n"
"     notice, this list of conditions and the following disclaimer.\n"
"\n"
"   * Redistributions in binary form must reproduce the above\n"
"     copyright notice, this list of conditions and the following\n"
"     disclaimer in the documentation and/or other materials provided\n"
"     with the distribution.\n"
"\n"
"   * Neither the name of the authors nor the names of its\n"
"     contributors may be used to endorse or promote products derived\n"
"     from this software without specific prior written permission.\n"
"\n"
" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
" \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n"
" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n"
" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n"
" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
" POSSIBILITY OF SUCH DAMAGE.\n"
"*/\n"
"\n"
"/**\n"
" * Device kernel for velocity gradients\n"
" */\n"
"\n"
"#define DEFINE_SET_CONVECT_RST_KERNEL(LX, CHUNKS)                              \\\n"
"__kernel void set_convect_rst_kernel_lx##LX(__global double * __restrict__ cr,   \\\n"
"                                   __global double * __restrict__ cs,            \\\n"
"                                   __global double * __restrict__ ct,            \\\n"
"                                   __global const double * __restrict__ cx,      \\\n"
"                                   __global const double * __restrict__ cy,      \\\n"
"                                   __global const double * __restrict__ cz,      \\\n"
"                                   __global const double * __restrict__ drdx,    \\\n"
"                                   __global const double * __restrict__ dsdx,    \\\n"
"                                   __global const double * __restrict__ dtdx,    \\\n"
"                                   __global const double * __restrict__ drdy,    \\\n"
"                                   __global const double * __restrict__ dsdy,    \\\n"
"                                   __global const double * __restrict__ dtdy,    \\\n"
"                                   __global const double * __restrict__ drdz,    \\\n"
"                                   __global const double * __restrict__ dsdz,    \\\n"
"                                   __global const double * __restrict__ dtdz,    \\\n"
"                                   __global const double * __restrict__ w3) {    \\\n"
"                                                                               \\\n"
"                                                                               \\\n"
"  int i,j,k;                                                                   \\\n"
"                                                                               \\\n"
"  const int e = get_group_id(0);                                               \\\n"
"  const int iii = get_local_id(0);                                             \\\n"
"  const int nchunks = (LX * LX * LX - 1) / CHUNKS + 1;                         \\\n"
"                                                                               \\\n"
"                                                                               \\\n"
"  j = iii;                                                                     \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int n = 0; n < nchunks; n++) {                                          \\\n"
"    const int ijk = iii + n * CHUNKS;                                          \\\n"
"    const int jk = ijk / LX;                                                   \\\n"
"    i = ijk - jk * LX;                                                         \\\n"
"    k = jk / LX;                                                               \\\n"
"    j = jk - k * LX;                                                           \\\n"
"    if ( i < LX && j < LX && k < LX) {                                         \\\n"
"                                                                               \\\n"
"      cr[ijk + e * LX * LX * LX] = w3[ijk]                                     \\\n"
"        * (drdx[ijk + e * LX * LX * LX] * cx[ijk + e * LX * LX * LX]           \\\n"
"           + drdy[ijk + e * LX * LX * LX] * cy[ijk + e * LX * LX * LX]         \\\n"
"           + drdz[ijk + e * LX * LX * LX] * cz[ijk + e * LX * LX * LX]);       \\\n"
"                                                                               \\\n"
"      cs[ijk + e * LX * LX * LX] = w3[ijk]                                     \\\n"
"        * (dsdx[ijk + e * LX * LX * LX] * cx[ijk + e * LX * LX * LX]           \\\n"
"           + dsdy[ijk + e * LX * LX * LX] * cy[ijk + e * LX * LX * LX]         \\\n"
"           + dsdz[ijk + e * LX * LX * LX] * cz[ijk + e * LX * LX * LX]);       \\\n"
"                                                                               \\\n"
"      ct[ijk + e * LX * LX * LX] = w3[ijk]                                     \\\n"
"        * (dtdx[ijk + e * LX * LX * LX] * cx[ijk + e * LX * LX * LX]           \\\n"
"           + dtdy[ijk + e * LX * LX * LX] * cy[ijk + e * LX * LX * LX]         \\\n"
"           + dtdz[ijk + e * LX * LX * LX] * cz[ijk + e * LX * LX * LX]);       \\\n"
"                                                                               \\\n"
"    }                                                                          \\\n"
"  }                                                                            \\\n"
"}\n"
"\n"
"DEFINE_SET_CONVECT_RST_KERNEL(12, 256)\n"
"DEFINE_SET_CONVECT_RST_KERNEL(11, 256)\n"
"DEFINE_SET_CONVECT_RST_KERNEL(10, 256)\n"
"DEFINE_SET_CONVECT_RST_KERNEL(9, 256)\n"
"DEFINE_SET_CONVECT_RST_KERNEL(8, 256)\n"
"DEFINE_SET_CONVECT_RST_KERNEL(7, 256)\n"
"DEFINE_SET_CONVECT_RST_KERNEL(6, 256)\n"
"DEFINE_SET_CONVECT_RST_KERNEL(5, 256)\n"
"DEFINE_SET_CONVECT_RST_KERNEL(4, 256)\n"
"DEFINE_SET_CONVECT_RST_KERNEL(3, 256)\n"
"DEFINE_SET_CONVECT_RST_KERNEL(2, 256)\n"
"\n"
"#endif // __MATH_SET_CONVECT_RST_KERNEL_CL__\n"
;
