const char *tensor_kernel =
"#ifndef __MATH_TENSOR_KERNEL_CL__\n"
"#define __MATH_TENSOR_KERNEL_CL__\n"
"/*\n"
" Copyright (c) 2022-2025, The Neko Authors\n"
" All rights reserved.\n"
"\n"
" Redistribution and use in source and binary forms, with or without\n"
" modification, are permitted provided that the following conditions\n"
" are met:\n"
"\n"
"   * Redistributions of source code must retain the above copyright\n"
"     notice, this list of conditions and the following disclaimer.\n"
"\n"
"   * Redistributions in binary form must reproduce the above\n"
"     copyright notice, this list of conditions and the following\n"
"     disclaimer in the documentation and/or other materials provided\n"
"     with the distribution.\n"
"\n"
"   * Neither the name of the authors nor the names of its\n"
"     contributors may be used to endorse or promote products derived\n"
"     from this software without specific prior written permission.\n"
"\n"
" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
" \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n"
" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n"
" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n"
" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
" POSSIBILITY OF SUCH DAMAGE.\n"
"*/\n"
"\n"
"#define DEFINE_TNSR3D_KERNEL(N)                                                \\\n"
"__kernel void tnsr3d_kernel_n##N(__global double  * __restrict__  v,             \\\n"
"                                 const int nv,                                 \\\n"
"                                 __global const double * __restrict__ u,         \\\n"
"                                 const int nu,                                 \\\n"
"                                 __global const double * __restrict__ A,         \\\n"
"                                 __global const double * __restrict__ Bt,        \\\n"
"                                 __global const double * __restrict__ Ct) {      \\\n"
"  __local double shwork[N*N*N];                                                  \\\n"
"  __local double shwork2[N*N*N];                                                 \\\n"
"                                                                               \\\n"
"  const int idx = get_local_id(0);                                             \\\n"
"  const int str = get_local_size(0);                                           \\\n"
"  const int e = get_group_id(0);                                               \\\n"
"                                                                               \\\n"
"  for (int ii = idx; ii< nu*nu*nv; ii += str){                                 \\\n"
"    double tmp = 0.0;                                                            \\\n"
"    int j = ii/nv;                                                             \\\n"
"    int i = ii - j*nv;                                                         \\\n"
"    for( int l = 0; l < nu; l++){                                              \\\n"
"      tmp += A[i+l*nv]*u[l+nu*j+e*nu*nu*nu];                                   \\\n"
"    }                                                                          \\\n"
"    shwork[ii] = tmp;                                                          \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int ijk = idx; ijk< nu*nv*nv; ijk += str){                              \\\n"
"    const int jk = ijk / nv;                                                   \\\n"
"    const int i = ijk - jk * nv;                                               \\\n"
"    const int k = jk / nv;                                                     \\\n"
"    const int j = jk - k * nv;                                                 \\\n"
"    double tmp = 0.0;                                                            \\\n"
"    const int ik2 = i + k*nv*nu;                                               \\\n"
"    for( int l = 0; l < nu; l++){                                              \\\n"
"      tmp += Bt[l+j*nu]*shwork[l*nv+ik2];                                      \\\n"
"    }                                                                          \\\n"
"    shwork2[ijk] = tmp;                                                        \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int ijk = idx; ijk< nv*nv*nv; ijk += str){                              \\\n"
"    const int jk = ijk / nv;                                                   \\\n"
"    const int i = ijk - jk * nv;                                               \\\n"
"    const int k = jk / nv;                                                     \\\n"
"    const int j = jk - k * nv;                                                 \\\n"
"    double tmp = 0.0;                                                            \\\n"
"    const int ij2 = i + j*nv;                                                  \\\n"
"    for( int l = 0; l < nu; l++){                                              \\\n"
"      tmp += Ct[l+k*nu]*shwork2[ij2 + l*nv*nv];                                \\\n"
"    }                                                                          \\\n"
"    v[ijk+e*nv*nv*nv] = tmp;                                                   \\\n"
"  }                                                                            \\\n"
"}\n"
"\n"
"DEFINE_TNSR3D_KERNEL(2)\n"
"DEFINE_TNSR3D_KERNEL(3)\n"
"DEFINE_TNSR3D_KERNEL(4)\n"
"DEFINE_TNSR3D_KERNEL(5)\n"
"DEFINE_TNSR3D_KERNEL(6)\n"
"DEFINE_TNSR3D_KERNEL(7)\n"
"DEFINE_TNSR3D_KERNEL(8)\n"
"DEFINE_TNSR3D_KERNEL(9)\n"
"DEFINE_TNSR3D_KERNEL(10)\n"
"DEFINE_TNSR3D_KERNEL(11)\n"
"DEFINE_TNSR3D_KERNEL(12)\n"
"DEFINE_TNSR3D_KERNEL(13)\n"
"DEFINE_TNSR3D_KERNEL(14)\n"
"DEFINE_TNSR3D_KERNEL(15)\n"
"DEFINE_TNSR3D_KERNEL(16)\n"
"\n"
"#define DEFINE_TNSR3D_EL_KERNEL(N)                                             \\\n"
"__kernel void tnsr3d_el_kernel_n##N(__global double  * __restrict__  v,          \\\n"
"                                    const int nv,                              \\\n"
"                                    __global const double * __restrict__ u,      \\\n"
"                                    const int nu,                              \\\n"
"                                    __global const double * __restrict__ A,      \\\n"
"                                    __global const double * __restrict__ Bt,     \\\n"
"                                    __global const double * __restrict__ Ct,     \\\n"
"                                    __global const int * __restrict__ elements,\\\n"
"                                    const int n_points) {                      \\\n"
"  __local double shwork[N*N*N];                                                  \\\n"
"  __local double shwork2[N*N*N];                                                 \\\n"
"                                                                               \\\n"
"  const int idx = get_local_id(0);                                             \\\n"
"  const int str = get_local_size(0);                                           \\\n"
"  const int pt = get_group_id(0);                                              \\\n"
"  const int e = elements[pt];                                                  \\\n"
"                                                                               \\\n"
"  for (int ii = idx; ii< nu*nu*nv; ii += str) {                                \\\n"
"    double tmp = 0.0;                                                            \\\n"
"    int j = ii/nv;                                                             \\\n"
"    int i = ii - j*nv;                                                         \\\n"
"    for( int l = 0; l < nu; l++){                                              \\\n"
"      tmp += A[i+l*nv+pt*nv*nu]*u[l+nu*j+e*nu*nu*nu];                          \\\n"
"    }                                                                          \\\n"
"    shwork[ii] = tmp;                                                          \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int ijk = idx; ijk< nu*nv*nv; ijk += str) {                             \\\n"
"    const int jk = ijk / nv;                                                   \\\n"
"    const int i = ijk - jk * nv;                                               \\\n"
"    const int k = jk / nv;                                                     \\\n"
"    const int j = jk - k * nv;                                                 \\\n"
"    double tmp = 0.0;                                                            \\\n"
"    const int ik2 = i + k*nv*nu;                                               \\\n"
"    for( int l = 0; l < nu; l++){                                              \\\n"
"      tmp += Bt[l+j*nu+pt*nv*nu]*shwork[l*nv+ik2];                             \\\n"
"    }                                                                          \\\n"
"    shwork2[ijk] = tmp;                                                        \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int ijk = idx; ijk< nv*nv*nv; ijk += str) {                             \\\n"
"    const int jk = ijk / nv;                                                   \\\n"
"    const int i = ijk - jk * nv;                                               \\\n"
"    const int k = jk / nv;                                                     \\\n"
"    const int j = jk - k * nv;                                                 \\\n"
"    double tmp = 0.0;                                                            \\\n"
"    const int ij2 = i + j*nv;                                                  \\\n"
"    for( int l = 0; l < nu; l++){                                              \\\n"
"      tmp += Ct[l+k*nu+pt*nv*nu]*shwork2[ij2 + l*nv*nv];                       \\\n"
"    }                                                                          \\\n"
"    v[ijk+pt*nv*nv*nv] = tmp;                                                  \\\n"
"  }                                                                            \\\n"
"}\n"
"\n"
"DEFINE_TNSR3D_EL_KERNEL(2)\n"
"DEFINE_TNSR3D_EL_KERNEL(3)\n"
"DEFINE_TNSR3D_EL_KERNEL(4)\n"
"DEFINE_TNSR3D_EL_KERNEL(5)\n"
"DEFINE_TNSR3D_EL_KERNEL(6)\n"
"DEFINE_TNSR3D_EL_KERNEL(7)\n"
"DEFINE_TNSR3D_EL_KERNEL(8)\n"
"DEFINE_TNSR3D_EL_KERNEL(9)\n"
"DEFINE_TNSR3D_EL_KERNEL(10)\n"
"DEFINE_TNSR3D_EL_KERNEL(11)\n"
"DEFINE_TNSR3D_EL_KERNEL(12)\n"
"DEFINE_TNSR3D_EL_KERNEL(13)\n"
"DEFINE_TNSR3D_EL_KERNEL(14)\n"
"\n"
"#endif // __MATH_TENSOR_KERNEL_CL__\n"
;
