const char *pnpn_res_kernel =
"/*\n"
" Copyright (c) 2022, The Neko Authors\n"
" All rights reserved.\n"
" Redistribution and use in source and binary forms, with or without\n"
" modification, are permitted provided that the following conditions\n"
" are met:\n"
"   * Redistributions of source code must retain the above copyright\n"
"     notice, this list of conditions and the following disclaimer.\n"
"   * Redistributions in binary form must reproduce the above\n"
"     copyright notice, this list of conditions and the following\n"
"     disclaimer in the documentation and/or other materials provided\n"
"     with the distribution.\n"
"   * Neither the name of the authors nor the names of its\n"
"     contributors may be used to endorse or promote products derived\n"
"     from this software without specific prior written permission.\n"
" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
" \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n"
" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n"
" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n"
" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
" POSSIBILITY OF SUCH DAMAGE.\n"
"*/\n"
"\n"
"#ifndef __FLUID_PNPN_RES_KERNEL__\n"
"#define __FLUID_PNPN_RES_KERNEL__\n"
"\n"
"__kernel void prs_res_part1_kernel(__global double * __restrict__ ta1,\n"
"                                   __global double * __restrict__ ta2,\n"
"                                   __global double * __restrict__ ta3,\n"
"                                   __global const double * __restrict__ wa1,\n"
"                                   __global const double * __restrict__ wa2,\n"
"                                   __global const double * __restrict__ wa3,\n"
"                                   __global const double * __restrict__ f_u,\n"
"                                   __global const double * __restrict__ f_v,\n"
"                                   __global const double * __restrict__ f_w,\n"
"                                   __global const double * __restrict__ B,\n"
"                                   __global double * __restrict__ h1,\n"
"                                   const double mu,\n"
"                                   const double rho,\n"
"                                   const int n) {\n"
"  \n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"  const double inv_rho = 1.0 / rho;\n"
"  \n"
"  for (int i = idx; i < n; i += str) {\n"
"    h1[i] = inv_rho;\n"
"    ta1[i] = (f_u[i] / rho) - ((wa1[i] * (mu / rho)) * B[i]);\n"
"    ta2[i] = (f_v[i] / rho) - ((wa2[i] * (mu / rho)) * B[i]);\n"
"    ta3[i] = (f_w[i] / rho) - ((wa3[i] * (mu / rho)) * B[i]);\n"
"  }\n"
"\n"
"}\n"
"\n"
"\n"
"__kernel void prs_res_part2_kernel(__global double * __restrict__ p_res,\n"
"                                   __global const double * __restrict__ wa1,\n"
"                                   __global const double * __restrict__ wa2,\n"
"                                   __global const double * __restrict__ wa3,\n"
"                                   const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"  \n"
"  for (int i = idx; i < n; i += str) {\n"
"    p_res[i] = (-p_res[i]) + (wa1[i] + wa2[i] + wa3[i]);\n"
"  }\n"
"}\n"
"\n"
"\n"
"__kernel void prs_res_part3_kernel(__global double * __restrict__ p_res,\n"
"                                   __global const double * __restrict__ ta1,\n"
"                                   __global const double * __restrict__ ta2,\n"
"                                   __global const double * __restrict__ ta3,\n"
"                                   const double dtbd,\n"
"                                   const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"  \n"
"  for (int i = idx; i < n; i += str) {\n"
"    p_res[i] = p_res[i] - (dtbd * (ta1[i] + ta2[i] + ta3[i]));\n"
"  }\n"
"}\n"
"\n"
"__kernel void vel_res_update_kernel(__global double * __restrict__ u_res,\n"
"                                    __global double * __restrict__ v_res,\n"
"                                    __global double * __restrict__ w_res,\n"
"                                    __global const double * __restrict__ ta1,\n"
"                                    __global const double * __restrict__ ta2,\n"
"                                    __global const double * __restrict__ ta3,\n"
"                                    __global const double * __restrict__ f_u,\n"
"                                    __global const double * __restrict__ f_v,\n"
"                                    __global const double * __restrict__ f_w,\n"
"                                    const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    u_res[i] = (-u_res[i]) - ta1[i] + f_u[i];\n"
"    v_res[i] = (-v_res[i]) - ta2[i] + f_v[i];\n"
"    w_res[i] = (-w_res[i]) - ta3[i] + f_w[i];\n"
"  }\n"
"\n"
"}\n"
"\n"
"#endif // __FLUID_PNPN_RES_KERNEL__\n";
