const char *rhs_maker_kernel =
"/*\n"
" Copyright (c) 2022, The Neko Authors\n"
" All rights reserved.\n"
"\n"
" Redistribution and use in source and binary forms, with or without\n"
" modification, are permitted provided that the following conditions\n"
" are met:\n"
"\n"
"   * Redistributions of source code must retain the above copyright\n"
"     notice, this list of conditions and the following disclaimer.\n"
"\n"
"   * Redistributions in binary form must reproduce the above\n"
"     copyright notice, this list of conditions and the following\n"
"     disclaimer in the documentation and/or other materials provided\n"
"     with the distribution.\n"
"\n"
"   * Neither the name of the authors nor the names of its\n"
"     contributors may be used to endorse or promote products derived\n"
"     from this software without specific prior written permission.\n"
"\n"
" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
" \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n"
" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n"
" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n"
" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
" POSSIBILITY OF SUCH DAMAGE.\n"
"*/\n"
"\n"
"#ifndef __COMMON_RHS_MAKER_KENEL__\n"
"#define __COMMON_RHS_MAKER_KENEL__\n"
"\n"
"__kernel void sumab_kernel(__global double * __restrict__ u,\n"
"                           __global double * __restrict__ v,\n"
"                           __global double * __restrict__ w,\n"
"                           __global const double * __restrict__ uu,\n"
"                           __global const double * __restrict__ vv,\n"
"                           __global const double * __restrict__ ww,\n"
"                           __global const double * __restrict__ ulag1,\n"
"                           __global const double * __restrict__ ulag2,\n"
"                           __global const double * __restrict__ vlag1,\n"
"                           __global const double * __restrict__ vlag2,\n"
"                           __global const double * __restrict__ wlag1,\n"
"                           __global const double * __restrict__ wlag2,\n"
"                           const double ab1,\n"
"                           const double ab2,\n"
"                           const double ab3,\n"
"                           const int nab,\n"
"                           const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    u[i] = ab1 * uu[i] + ab2 * ulag1[i];\n"
"    v[i] = ab1 * vv[i] + ab2 * vlag1[i];\n"
"    w[i] = ab1 * ww[i] + ab2 * wlag1[i];\n"
"  }\n"
"\n"
"  if (nab == 3) {\n"
"    for (int i = idx; i < n; i += str) {\n"
"      u[i] = u[i] + ab3 * ulag2[i];\n"
"      v[i] = v[i] + ab3 * vlag2[i];\n"
"      w[i] = w[i] + ab3 * wlag2[i];\n"
"    }\n"
"  }\n"
"\n"
"}\n"
"\n"
"__kernel void makeext_kernel(__global double * __restrict__ abx1,\n"
"                             __global double * __restrict__ aby1,\n"
"                             __global double * __restrict__ abz1,\n"
"                             __global double * __restrict__ abx2,\n"
"                             __global double * __restrict__ aby2,\n"
"                             __global double * __restrict__ abz2,\n"
"                             __global double * __restrict__ bfx,\n"
"                             __global double * __restrict__ bfy,\n"
"                             __global double * __restrict__ bfz,\n"
"                             const double rho,\n"
"                             const double ab1,\n"
"                             const double ab2,\n"
"                             const double ab3,\n"
"                             const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    double ta1_val = ab2 * abx1[i] + ab3 * abx2[i];\n"
"    double ta2_val = ab2 * aby1[i] + ab3 * aby2[i];\n"
"    double ta3_val = ab2 * abz1[i] + ab3 * abz2[i];\n"
"\n"
"    abx2[i] = abx1[i];\n"
"    aby2[i] = aby1[i];\n"
"    abz2[i] = abz1[i];\n"
"    abx1[i] = bfx[i];\n"
"    aby1[i] = bfy[i];\n"
"    abz1[i] = bfz[i];\n"
"\n"
"    bfx[i] = (ab1 * bfx[i] + ta1_val) * rho;\n"
"    bfy[i] = (ab1 * bfy[i] + ta2_val) * rho;\n"
"    bfz[i] = (ab1 * bfz[i] + ta3_val) * rho;\n"
"  }\n"
"\n"
"}\n"
"\n"
"__kernel void scalar_makeext_kernel(__global double * __restrict__ fs_lag,\n"
"                                    __global double * __restrict__ fs_laglag,\n"
"                                    __global double * __restrict__ fs,\n"
"                                    const double rho,\n"
"                                    const double ext1,\n"
"                                    const double ext2,\n"
"                                    const double ext3,\n"
"                                    const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    double ta1_val = ext2 * fs_lag[i] + ext3 * fs_laglag[i];\n"
"\n"
"    fs_laglag[i] = fs_lag[i];\n"
"    fs_lag[i] = fs[i];\n"
"\n"
"    fs[i] = (ext1 * fs[i] + ta1_val) * rho;\n"
"  }\n"
"\n"
"}\n"
"\n"
"__kernel void makebdf_kernel(__global const double * __restrict__ ulag1,\n"
"                             __global const double * __restrict__ ulag2,\n"
"                             __global const double * __restrict__ vlag1,\n"
"                             __global const double * __restrict__ vlag2,\n"
"                             __global const double * __restrict__ wlag1,\n"
"                             __global const double * __restrict__ wlag2,\n"
"                             __global double * __restrict__ bfx,\n"
"                             __global double * __restrict__ bfy,\n"
"                             __global double * __restrict__ bfz,\n"
"                             __global const double * __restrict__ u,\n"
"                             __global const double * __restrict__ v,\n"
"                             __global const double * __restrict__ w,\n"
"                             __global const double * __restrict__ B,\n"
"                             const double rho,\n"
"                             const double dt,\n"
"                             const double bd2,\n"
"                             const double bd3,\n"
"                             const double bd4,\n"
"                             const int nbd,\n"
"                             const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    double tb1_val = u[i] * B[i] * bd2;\n"
"    double tb2_val = v[i] * B[i] * bd2;\n"
"    double tb3_val = w[i] * B[i] * bd2;\n"
"\n"
"    double ta1_val = ulag1[i] * B[i] * bd3;\n"
"    double ta2_val = vlag1[i] * B[i] * bd3;\n"
"    double ta3_val = wlag1[i] * B[i] * bd3;\n"
"\n"
"    tb1_val += ta1_val;\n"
"    tb2_val += ta2_val;\n"
"    tb3_val += ta3_val;\n"
"\n"
"    if (nbd == 3) {\n"
"      tb1_val += ulag2[i] * B[i] * bd4;\n"
"      tb2_val += vlag2[i] * B[i] * bd4;\n"
"      tb3_val += wlag2[i] * B[i] * bd4;\n"
"    }\n"
"\n"
"    bfx[i] = bfx[i] + tb1_val * (rho / dt);\n"
"    bfy[i] = bfy[i] + tb2_val * (rho / dt);\n"
"    bfz[i] = bfz[i] + tb3_val * (rho / dt);\n"
"  }\n"
"\n"
"}\n"
"\n"
"__kernel void scalar_makebdf_kernel(__global const double * __restrict__ s_lag,\n"
"                                    __global const double * __restrict__ s_laglag,\n"
"                                    __global double * __restrict__ fs,\n"
"                                    __global const double * __restrict__ s,\n"
"                                    __global const double * __restrict__ B,\n"
"                                    const double rho,\n"
"                                    const double dt,\n"
"                                    const double bd2,\n"
"                                    const double bd3,\n"
"                                    const double bd4,\n"
"                                    const int nbd,\n"
"                                    const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    double tb1_val = s[i] * B[i] * bd2;\n"
"\n"
"    double ta1_val = s_lag[i] * B[i] * bd3;\n"
"\n"
"    tb1_val += ta1_val;\n"
"\n"
"    if (nbd == 3) {\n"
"      tb1_val += s_laglag[i] * B[i] * bd4;\n"
"    }\n"
"\n"
"    fs[i] = fs[i] + tb1_val * (rho / dt);\n"
"  }\n"
"\n"
"}\n"
"\n"
"__kernel void makeoifs_kernel(__global const double * __restrict__ phi_x,\n"
"                             __global const double * __restrict__ phi_y,\n"
"                             __global const double * __restrict__ phi_z,\n"
"                             __global double * __restrict__ bf_x,\n"
"                             __global double * __restrict__ bf_y,\n"
"                             __global double * __restrict__ bf_z,\n"
"                             const double rho,\n"
"                             const double dt,\n"
"                             const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"\n"
"    bf_x[i] = bf_x[i] + phi_x[i] * (rho / dt);\n"
"    bf_y[i] = bf_y[i] + phi_y[i] * (rho / dt);\n"
"    bf_z[i] = bf_z[i] + phi_z[i] * (rho / dt);\n"
"  }\n"
"\n"
"}\n"
"\n"
"__kernel void scalar_makeoifs_kernel(__global const double * __restrict__ phi_s,\n"
"                                    __global double * __restrict__ bf_s,\n"
"                                    const double rho,\n"
"                                    const double dt,\n"
"                                    const int n) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"\n"
"    bf_s[i] = bf_s[i] + phi_s[i] * (rho / dt);\n"
"  }\n"
"\n"
"}\n"
"\n"
"\n"
"#endif // __COMMON_RHS_MAKER_KENEL__\n";
