const char *dong_outflow_kernel =
"/*\n"
" Copyright (c) 2022-2023, The Neko Authors\n"
" All rights reserved.\n"
"\n"
" Redistribution and use in source and binary forms, with or without\n"
" modification, are permitted provided that the following conditions\n"
" are met:\n"
"\n"
"   * Redistributions of source code must retain the above copyright\n"
"     notice, this list of conditions and the following disclaimer.\n"
"\n"
"   * Redistributions in binary form must reproduce the above\n"
"     copyright notice, this list of conditions and the following\n"
"     disclaimer in the documentation and/or other materials provided\n"
"     with the distribution.\n"
"\n"
"   * Neither the name of the authors nor the names of its\n"
"     contributors may be used to endorse or promote products derived\n"
"     from this software without specific prior written permission.\n"
"\n"
" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
" \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n"
" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n"
" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n"
" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
" POSSIBILITY OF SUCH DAMAGE.\n"
"*/\n"
"\n"
"#ifndef __BC_DONG_OUTFLOW_KERNEL__\n"
"#define __BC_DONG_OUTFLOW_KERNEL__\n"
"\n"
"/**\n"
" * Device kernel for scalar apply for a dong outflow condition\n"
" */\n"
"__kernel\n"
"void dong_outflow_apply_scalar_kernel(__global const int * __restrict__ msk,\n"
"				      __global double * __restrict__ x,\n"
"				      __global const double * normal_x,\n"
"				      __global const double * normal_y,\n"
"				      __global const double * normal_z,\n"
"				      __global const double * u,\n"
"				      __global const double * v,\n"
"				      __global const double * w,\n"
"				      const double uinf,\n"
"				      const double delta,\n"
"				      const int m) {\n"
"  \n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < m; i += str) {\n"
"    const int k = msk[i + 1] - 1;\n"
"    const double uk = u[k];\n"
"    const double vk = v[k];\n"
"    const double wk = w[k];\n"
"    const double vn = uk*normal_x[i] + vk*normal_y[i] + wk*normal_z[i];\n"
"    const double S0 = 0.5*(1.0 - tanh(vn/(uinf*delta)));\n"
"    x[k] = -0.5*(uk*uk+vk*vk+wk*wk)*S0;\n"
"  }\n"
"}\n"
"\n"
"#endif // __BC_DONG_OUTFLOW_KERNEL__\n";
