const char *symmetry_kernel =
"/*\n"
" Copyright (c) 2021-2022, The Neko Authors\n"
" All rights reserved.\n"
"\n"
" Redistribution and use in source and binary forms, with or without\n"
" modification, are permitted provided that the following conditions\n"
" are met:\n"
"\n"
"   * Redistributions of source code must retain the above copyright\n"
"     notice, this list of conditions and the following disclaimer.\n"
"\n"
"   * Redistributions in binary form must reproduce the above\n"
"     copyright notice, this list of conditions and the following\n"
"     disclaimer in the documentation and/or other materials provided\n"
"     with the distribution.\n"
"\n"
"   * Neither the name of the authors nor the names of its\n"
"     contributors may be used to endorse or promote products derived\n"
"     from this software without specific prior written permission.\n"
"\n"
" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
" \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n"
" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n"
" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n"
" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
" POSSIBILITY OF SUCH DAMAGE.\n"
"*/\n"
"\n"
"#ifndef __BC_SYMETRY_KERNEL__\n"
"#define __BC_SYMETRY_KERNEL__\n"
"\n"
"/**\n"
" * Device kernel for vector apply for a symmetry condition\n"
" */\n"
"__kernel void symmetry_apply_vector_kernel(__global const int *xmsk,\n"
"                                           __global const int *ymsk,\n"
"                                           __global const int *zmsk,\n"
"                                           __global double *x,\n"
"                                           __global double *y,\n"
"                                           __global double *z,\n"
"                                           const int m,\n"
"                                           const int n,\n"
"                                           const int l) {\n"
"\n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_global_size(0);\n"
"\n"
"  for (int i = idx; i < m; i += str) {\n"
"    const int k = (xmsk[i+1] - 1);\n"
"    x[k] = 0.0;\n"
"  }\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    const int k = (ymsk[i+1] - 1);\n"
"    y[k] = 0.0;\n"
"  }\n"
"\n"
"  for (int i = idx; i < l; i += str) {\n"
"    const int k = (zmsk[i+1] - 1);\n"
"    z[k] = 0.0;\n"
"  }\n"
"  \n"
"}\n"
"\n"
"#endif // ___BC_SYMETRY_KERNEL___\n";
