#!/bin/sh -e

prefix=/scratch/baconnet/software/neko
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir_pkg=${prefix}/include/neko
FC=mpif90
FCFLAGS='-I/scratch/baconnet/software/anaconda3/pkgs/json-fortran-8.3.0-h2a4ca65_0/include  -g -O2'
files="FST-imp/global_params.f90 FST-imp/spectrum.f90 FST-imp/sphere.f90 FST-imp/spec.f90 FST-imp/turbu.f90 FST-imp/FST.f90"
printf "\n%s\n" 'N E K O build tool, Version 0.6.99'
printf "%s\n" '(build: 2023-10-25 on x86_64-pc-linux-gnu using gnu)'


if [ -z "$1" ]
  then
      echo "No user file provided"
      exit 1
fi
printf '\n%s' "Building user NEKO ..."
rm -f usr_driver.f90
cat >> usr_driver.f90 << _ACEOF
program usrneko
  use neko
  use user
  type(case_t) :: C
  
  call user_setup(C%usr)
  call neko_init(C)
  call neko_solve(C)
  call neko_finalize(C)


end program usrneko
_ACEOF

$FC $FCFLAGS -I$includedir_pkg -L$libdir $files $1 usr_driver.f90\
    -lneko -L/scratch/baconnet/externals/gslib/build/lib -L/scratch/baconnet/externals/gslib/build  -L/scratch/baconnet/software/anaconda3/pkgs/json-fortran-8.3.0-h2a4ca65_0/lib/ -ljsonfortran  -lgs  -llapack -lblas    -o neko

rm -f usr_driver.f90

printf "%s\n" ' done!'
