#!/usr/bin/env python3

"""
Purpose of this program is to read the bb.txt, sphere.dat and fst_spectrum.dat
files generated by the FST code;
"""

import numpy as np
import matplotlib.pyplot as plt
from os.path import join

path = "/scratch/baconnet/simulations/neko/fst_sandbox"

fst_spectrum_data = np.genfromtxt(join(path,"fst_spectrum.csv"), skip_header=1, delimiter=",")
fst = {"shell_no": fst_spectrum_data[0, :],
       "kx": fst_spectrum_data[:, 1],
       "ky": fst_spectrum_data[:, 2],
       "kz": fst_spectrum_data[:, 3],
       "u_amp": fst_spectrum_data[:, 4],
       "v_amp": fst_spectrum_data[:, 5],
       "w_amp": fst_spectrum_data[:, 6],
       "u_hat_pn1": fst_spectrum_data[:, 7],
       "u_hat_pn2": fst_spectrum_data[:, 8],
       "u_hat_pn3": fst_spectrum_data[:, 9]}

k2 = fst["kx"]**2 + fst["ky"]**2 + fst["kz"]**2
E = fst["u_amp"]**2 + fst["v_amp"]**2 + fst["w_amp"]**2

# for i in range(20):
#     print(fst["u_hat_pn1"][i]**2 + fst["u_hat_pn2"][i]**2 + fst["u_hat_pn3"][i]**2)

plt.loglog(np.sqrt(k2), E, '+')
plt.xlabel(r"$k$")
plt.ylabel(r"$E(k)$")
plt.tight_layout()
plt.show()
