const char *coef_kernel =
"#ifndef __SEM_COEF_KERNEL_CL__\n"
"#define __SEM_COEF_KERNEL_CL__\n"
"/*\n"
" Copyright (c) 2022-2025, The Neko Authors\n"
" All rights reserved.\n"
"\n"
" Redistribution and use in source and binary forms, with or without\n"
" modification, are permitted provided that the following conditions\n"
" are met:\n"
"\n"
"   * Redistributions of source code must retain the above copyright\n"
"     notice, this list of conditions and the following disclaimer.\n"
"\n"
"   * Redistributions in binary form must reproduce the above\n"
"     copyright notice, this list of conditions and the following\n"
"     disclaimer in the documentation and/or other materials provided\n"
"     with the distribution.\n"
"\n"
"   * Neither the name of the authors nor the names of its\n"
"     contributors may be used to endorse or promote products derived\n"
"     from this software without specific prior written permission.\n"
"\n"
" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
" \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n"
" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n"
" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n"
" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
" POSSIBILITY OF SUCH DAMAGE.\n"
"*/\n"
"\n"
"/**\n"
" * Device kernel for coef geometry\n"
" */\n"
"#define DEFINE_GENERATE_GEO_KERNEL(LX, CHUNKS)                                 \\\n"
"__kernel                                                                       \\\n"
"void coef_generate_geo_kernel_lx##LX(__global double * __restrict__ G11,         \\\n"
"                                     __global double * __restrict__ G12,         \\\n"
"                                     __global double * __restrict__ G13,         \\\n"
"                                     __global double * __restrict__ G22,         \\\n"
"                                     __global double * __restrict__ G23,         \\\n"
"                                     __global double * __restrict__ G33,         \\\n"
"                                     __global const double * __restrict__ drdx,  \\\n"
"                                     __global const double * __restrict__ drdy,  \\\n"
"                                     __global const double * __restrict__ drdz,  \\\n"
"                                     __global const double * __restrict__ dsdx,  \\\n"
"                                     __global const double * __restrict__ dsdy,  \\\n"
"                                     __global const double * __restrict__ dsdz,  \\\n"
"                                     __global const double * __restrict__ dtdx,  \\\n"
"                                     __global const double * __restrict__ dtdy,  \\\n"
"                                     __global const double * __restrict__ dtdz,  \\\n"
"                                     __global const double * __restrict__ jacinv,\\\n"
"                                     __global const double * __restrict__ w3,    \\\n"
"                                     const int gdim) {                         \\\n"
"                                                                               \\\n"
"  int i,j,k;                                                                   \\\n"
"                                                                               \\\n"
"  const int e = get_group_id(0);                                               \\\n"
"  const int iii = get_local_id(0);                                             \\\n"
"  const int nchunks = (LX * LX * LX - 1) / CHUNKS + 1;                         \\\n"
"                                                                               \\\n"
"  __local double shw3[LX * LX * LX];                                             \\\n"
"                                                                               \\\n"
"  j = iii;                                                                     \\\n"
"  while( j < (LX * LX * LX)) {                                                 \\\n"
"    const int i = j + e * LX * LX * LX;                                        \\\n"
"    G11[i] = (drdx[i]*drdx[i] + drdy[i]*drdy[i] + drdz[i]*drdz[i]) * jacinv[i];\\\n"
"    G22[i] = (dsdx[i]*dsdx[i] + dsdy[i]*dsdy[i] + dsdz[i]*dsdz[i]) * jacinv[i];\\\n"
"    G33[i] = (dtdx[i]*dtdx[i] + dtdy[i]*dtdy[i] + dtdz[i]*dtdz[i]) * jacinv[i];\\\n"
"                                                                               \\\n"
"    G12[i] = (drdx[i]*dsdx[i] + drdy[i]*dsdy[i] + drdz[i]*dsdz[i]) * jacinv[i];\\\n"
"    G13[i] = (drdx[i]*dtdx[i] + drdy[i]*dtdy[i] + drdz[i]*dtdz[i]) * jacinv[i];\\\n"
"    G23[i] = (dsdx[i]*dtdx[i] + dsdy[i]*dtdy[i] + dsdz[i]*dtdz[i]) * jacinv[i];\\\n"
"                                                                               \\\n"
"    shw3[j] = w3[j];                                                           \\\n"
"    j = j + CHUNKS;                                                            \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int n = 0; n < nchunks; n++) {                                          \\\n"
"    const int ijk = iii + n * CHUNKS;                                          \\\n"
"    const int jk = ijk / LX;                                                   \\\n"
"    i = ijk - jk * LX;                                                         \\\n"
"    k = jk / LX;                                                               \\\n"
"    j = jk - k * LX;                                                           \\\n"
"    if ( i < LX && j < LX && k < LX) {                                         \\\n"
"      G11[ijk + e * LX * LX * LX] *= shw3[ijk];                                \\\n"
"      G12[ijk + e * LX * LX * LX] *= shw3[ijk];                                \\\n"
"      G13[ijk + e * LX * LX * LX] *= shw3[ijk];                                \\\n"
"      G22[ijk + e * LX * LX * LX] *= shw3[ijk];                                \\\n"
"      G23[ijk + e * LX * LX * LX] *= shw3[ijk];                                \\\n"
"      G33[ijk + e * LX * LX * LX] *= shw3[ijk];                                \\\n"
"    }                                                                          \\\n"
"  }                                                                            \\\n"
"}\n"
"\n"
"DEFINE_GENERATE_GEO_KERNEL(2, 256)\n"
"DEFINE_GENERATE_GEO_KERNEL(3, 256)\n"
"DEFINE_GENERATE_GEO_KERNEL(4, 256)\n"
"DEFINE_GENERATE_GEO_KERNEL(5, 256)\n"
"DEFINE_GENERATE_GEO_KERNEL(6, 256)\n"
"DEFINE_GENERATE_GEO_KERNEL(7, 256)\n"
"DEFINE_GENERATE_GEO_KERNEL(8, 256)\n"
"DEFINE_GENERATE_GEO_KERNEL(9, 256)\n"
"DEFINE_GENERATE_GEO_KERNEL(10, 256)\n"
"DEFINE_GENERATE_GEO_KERNEL(11, 256)\n"
"DEFINE_GENERATE_GEO_KERNEL(12, 256)\n"
"DEFINE_GENERATE_GEO_KERNEL(13, 256)\n"
"DEFINE_GENERATE_GEO_KERNEL(14, 256)\n"
"DEFINE_GENERATE_GEO_KERNEL(15, 256)\n"
"DEFINE_GENERATE_GEO_KERNEL(16, 256)\n"
"\n"
"/**\n"
" * Device kernel for coef dxyz\n"
" */\n"
"#define DEFINE_GENERATE_DXYZ_KERNEL(LX, CHUNKS)                                \\\n"
"__kernel                                                                       \\\n"
"void coef_generate_dxyz_kernel_lx##LX(__global double * __restrict__ dxdr,       \\\n"
"                                      __global double * __restrict__ dydr,       \\\n"
"                                      __global double * __restrict__ dzdr,       \\\n"
"                                      __global double * __restrict__ dxds,       \\\n"
"                                      __global double * __restrict__ dyds,       \\\n"
"                                      __global double * __restrict__ dzds,       \\\n"
"                                      __global double * __restrict__ dxdt,       \\\n"
"                                      __global double * __restrict__ dydt,       \\\n"
"                                      __global double * __restrict__ dzdt,       \\\n"
"                                      __global const double * __restrict__ dx,   \\\n"
"                                      __global const double * __restrict__ dy,   \\\n"
"                                      __global const double * __restrict__ dz,   \\\n"
"                                      __global const double * __restrict__ x,    \\\n"
"                                      __global const double * __restrict__ y,    \\\n"
"                                      __global const double * __restrict__ z) {  \\\n"
"                                                                               \\\n"
"  int i,j,k;                                                                   \\\n"
"                                                                               \\\n"
"  const int e = get_group_id(0);                                               \\\n"
"  const int iii = get_local_id(0);                                             \\\n"
"  const int nchunks = (LX * LX * LX - 1) / CHUNKS + 1;                         \\\n"
"                                                                               \\\n"
"  __local double shdx[LX * LX];                                                  \\\n"
"  __local double shdy[LX * LX];                                                  \\\n"
"  __local double shdz[LX * LX];                                                  \\\n"
"                                                                               \\\n"
"  __local double  shu[LX * LX * LX];                                             \\\n"
"                                                                               \\\n"
"  if (iii < (LX * LX)) {                                                       \\\n"
"    shdx[iii] = dx[iii];                                                       \\\n"
"    shdy[iii] = dy[iii];                                                       \\\n"
"    shdz[iii] = dz[iii];                                                       \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  j = iii;                                                                     \\\n"
"  while(j < (LX * LX * LX)) {                                                  \\\n"
"    shu[j] = x[j + e * LX * LX * LX];                                          \\\n"
"    j = j + CHUNKS;                                                            \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int n = 0; n < nchunks; n++) {                                          \\\n"
"    const int ijk = iii + n * CHUNKS;                                          \\\n"
"    const int jk = ijk / LX;                                                   \\\n"
"    i = ijk - jk * LX;                                                         \\\n"
"    k = jk / LX;                                                               \\\n"
"    j = jk - k * LX;                                                           \\\n"
"    if ( i < LX && j < LX && k < LX) {                                         \\\n"
"      double rtmp = 0.0;                                                         \\\n"
"      double stmp = 0.0;                                                         \\\n"
"      double ttmp = 0.0;                                                         \\\n"
"      for (int l = 0; l < LX; l++) {                                           \\\n"
"        rtmp += shdx[i + l * LX] * shu[l + j * LX + k * LX * LX];              \\\n"
"        stmp += shdy[j + l * LX] * shu[i + l * LX + k * LX * LX];              \\\n"
"        ttmp += shdz[k + l * LX] * shu[i + j * LX + l * LX * LX];              \\\n"
"      }                                                                        \\\n"
"      dxdr[ijk + e * LX * LX * LX] = rtmp;                                     \\\n"
"      dxds[ijk + e * LX * LX * LX] = stmp;                                     \\\n"
"      dxdt[ijk + e * LX * LX * LX] = ttmp;                                     \\\n"
"    }                                                                          \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  j = iii;                                                                     \\\n"
"  while(j < (LX * LX * LX)) {                                                  \\\n"
"    shu[j] = y[j + e * LX * LX * LX];                                          \\\n"
"    j = j + CHUNKS;                                                            \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int n = 0; n < nchunks; n++) {                                          \\\n"
"    const int ijk = iii + n * CHUNKS;                                          \\\n"
"    const int jk = ijk / LX;                                                   \\\n"
"    i = ijk - jk * LX;                                                         \\\n"
"    k = jk / LX;                                                               \\\n"
"    j = jk - k * LX;                                                           \\\n"
"    if ( i < LX && j < LX && k < LX) {                                         \\\n"
"      double rtmp = 0.0;                                                         \\\n"
"      double stmp = 0.0;                                                         \\\n"
"      double ttmp = 0.0;                                                         \\\n"
"      for (int l = 0; l < LX; l++) {                                           \\\n"
"        rtmp += shdx[i + l * LX] * shu[l + j * LX + k * LX * LX];              \\\n"
"        stmp += shdy[j + l * LX] * shu[i + l * LX + k * LX * LX];              \\\n"
"        ttmp += shdz[k + l * LX] * shu[i + j * LX + l * LX * LX];              \\\n"
"      }                                                                        \\\n"
"      dydr[ijk + e * LX * LX * LX] = rtmp;                                     \\\n"
"      dyds[ijk + e * LX * LX * LX] = stmp;                                     \\\n"
"      dydt[ijk + e * LX * LX * LX] = ttmp;                                     \\\n"
"    }                                                                          \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  j = iii;                                                                     \\\n"
"  while(j < (LX * LX * LX)) {                                                  \\\n"
"    shu[j] = z[j + e * LX * LX * LX];                                          \\\n"
"    j = j + CHUNKS;                                                            \\\n"
"  }                                                                            \\\n"
"                                                                               \\\n"
"  barrier(CLK_LOCAL_MEM_FENCE);                                                \\\n"
"                                                                               \\\n"
"  for (int n = 0; n < nchunks; n++) {                                          \\\n"
"    const int ijk = iii + n * CHUNKS;                                          \\\n"
"    const int jk = ijk / LX;                                                   \\\n"
"    i = ijk - jk * LX;                                                         \\\n"
"    k = jk / LX;                                                               \\\n"
"    j = jk - k * LX;                                                           \\\n"
"    if ( i < LX && j < LX && k < LX) {                                         \\\n"
"      double rtmp = 0.0;                                                         \\\n"
"      double stmp = 0.0;                                                         \\\n"
"      double ttmp = 0.0;                                                         \\\n"
"      for (int l = 0; l < LX; l++) {                                           \\\n"
"        rtmp += shdx[i + l * LX] * shu[l + j * LX + k * LX * LX];              \\\n"
"        stmp += shdy[j + l * LX] * shu[i + l * LX + k * LX * LX];              \\\n"
"        ttmp += shdz[k + l * LX] * shu[i + j * LX + l * LX * LX];              \\\n"
"      }                                                                        \\\n"
"      dzdr[ijk + e * LX * LX * LX] = rtmp;                                     \\\n"
"      dzds[ijk + e * LX * LX * LX] = stmp;                                     \\\n"
"      dzdt[ijk + e * LX * LX * LX] = ttmp;                                     \\\n"
"    }                                                                          \\\n"
"  }                                                                            \\\n"
"}\n"
"\n"
"DEFINE_GENERATE_DXYZ_KERNEL(2, 256)\n"
"DEFINE_GENERATE_DXYZ_KERNEL(3, 256)\n"
"DEFINE_GENERATE_DXYZ_KERNEL(4, 256)\n"
"DEFINE_GENERATE_DXYZ_KERNEL(5, 256)\n"
"DEFINE_GENERATE_DXYZ_KERNEL(6, 256)\n"
"DEFINE_GENERATE_DXYZ_KERNEL(7, 256)\n"
"DEFINE_GENERATE_DXYZ_KERNEL(8, 256)\n"
"DEFINE_GENERATE_DXYZ_KERNEL(9, 256)\n"
"DEFINE_GENERATE_DXYZ_KERNEL(10, 256)\n"
"DEFINE_GENERATE_DXYZ_KERNEL(11, 256)\n"
"DEFINE_GENERATE_DXYZ_KERNEL(12, 256)\n"
"DEFINE_GENERATE_DXYZ_KERNEL(13, 256)\n"
"DEFINE_GENERATE_DXYZ_KERNEL(14, 256)\n"
"DEFINE_GENERATE_DXYZ_KERNEL(15, 256)\n"
"DEFINE_GENERATE_DXYZ_KERNEL(16, 256)\n"
"\n"
"/**\n"
" * Device kernel for coef drst\n"
" */\n"
"__kernel void coef_generate_drst_kernel(__global double * __restrict__ jac,\n"
"                                        __global double * __restrict__ jacinv,\n"
"                                        __global double * __restrict__ drdx,\n"
"                                        __global double * __restrict__ drdy,\n"
"                                        __global double * __restrict__ drdz,\n"
"                                        __global double * __restrict__ dsdx,\n"
"                                        __global double * __restrict__ dsdy,\n"
"                                        __global double * __restrict__ dsdz,\n"
"                                        __global double * __restrict__ dtdx,\n"
"                                        __global double * __restrict__ dtdy,\n"
"                                        __global double * __restrict__ dtdz,\n"
"                                        __global const double * __restrict__ dxdr,\n"
"                                        __global const double * __restrict__ dydr,\n"
"                                        __global const double * __restrict__ dzdr,\n"
"                                        __global const double * __restrict__ dxds,\n"
"                                        __global const double * __restrict__ dyds,\n"
"                                        __global const double * __restrict__ dzds,\n"
"                                        __global const double * __restrict__ dxdt,\n"
"                                        __global const double * __restrict__ dydt,\n"
"                                        __global const double * __restrict__ dzdt,\n"
"                                        const int n) {\n"
"                                \n"
"  const int idx = get_global_id(0);\n"
"  const int str = get_local_size(0) * get_num_groups(0);\n"
"  const double one = 1.0;\n"
"\n"
"  for (int i = idx; i < n; i += str) {\n"
"    jac[i] = (dxdr[i] * dyds[i] * dzdt[i])\n"
"           + (dxdt[i] * dydr[i] * dzds[i])\n"
"           + (dxds[i] * dydt[i] * dzdr[i])\n"
"           - (dxdr[i] * dydt[i] * dzds[i])\n"
"           - (dxds[i] * dydr[i] * dzdt[i])\n"
"           - (dxdt[i] * dyds[i] * dzdr[i]);\n"
"    jacinv[i] = one / jac[i];    \n"
"\n"
"    drdx[i] = dyds[i]*dzdt[i] - dydt[i]*dzds[i];\n"
"    drdy[i] = dxdt[i]*dzds[i] - dxds[i]*dzdt[i];\n"
"    drdz[i] = dxds[i]*dydt[i] - dxdt[i]*dyds[i];\n"
"    dsdx[i] = dydt[i]*dzdr[i] - dydr[i]*dzdt[i];\n"
"    dsdy[i] = dxdr[i]*dzdt[i] - dxdt[i]*dzdr[i];\n"
"    dsdz[i] = dxdt[i]*dydr[i] - dxdr[i]*dydt[i];\n"
"    dtdx[i] = dydr[i]*dzds[i] - dyds[i]*dzdr[i];\n"
"    dtdy[i] = dxds[i]*dzdr[i] - dxdr[i]*dzds[i];\n"
"    dtdz[i] = dxdr[i]*dyds[i] - dxds[i]*dydr[i];\n"
"\n"
"  }\n"
"\n"
"}\n"
"\n"
"#endif // __SEM_COEF_KERNEL_CL__\n"
;
