name: Intel Fortran

# Controls when the action will run.
on:
  push:
    branches:
      - develop
      - release/*
      - master

  workflow_dispatch:
  workflow_call:
    inputs:
      json-fortran-version:
        description: "The version of the JSON-Fortran library to use."
        type: string
        required: false
        default: "8.4.0"
      pfunit-version:
        description: "The version of the pFUnit library to use."
        type: string
        required: false
        default: "v4.15.0"

jobs:
  Intel:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        compiler: [ifx]
        precision: [sp, dp]
        backend: [cpu]
        include:
          - os: ubuntu-24.04
            setup-env: |
              wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
              echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
              sudo apt-get update -y
              sudo apt install -y intel-oneapi-compiler-fortran intel-oneapi-compiler-dpcpp-cpp intel-oneapi-mpi intel-oneapi-mpi-devel
              source /opt/intel/oneapi/setvars.sh
              sudo apt install -y autoconf automake autotools-dev libopenblas-dev make git m4 python3 python3-pip ca-certificates cmake
              INTEL_PATH=$(find /opt/intel/oneapi/compiler/ -name "${FC}" -type f | xargs dirname)
              export PATH=$INTEL_PATH:${PATH}
              printenv >> $GITHUB_ENV
              echo "os-version=$(lsb_release -ds | tr " " -)" >> $GITHUB_OUTPUT

    env:
      CC: icx
      FC: ${{ matrix.compiler }}
      RP: ${{ matrix.precision }}
      NEKO_EXEC: ${{ github.workspace }}/install/bin/neko
      MAKENEKO_EXEC: ${{ github.workspace }}/install/bin/makeneko
    name: ${{ matrix.os }} - ${{ matrix.compiler }} - ${{ matrix.backend }} - ${{ matrix.precision }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup env.
        id: setup-env
        run: ${{ matrix.setup-env }}

      - name: Setup dependencies
        id: setup-deps
        env:
          PFUNIT_VERSION: ${{ inputs.pfunit-version }}
          JSON_FORTRAN_VERSION: ${{ inputs.json-fortran-version }}
        run: |
          if [ -z "$PFUNIT_VERSION" ]; then PFUNIT_VERSION="v4.15.0"; fi
          if [ -z "$JSON_FORTRAN_VERSION" ]; then JSON_FORTRAN_VERSION="8.3.0"; fi

          echo "pfunit-version=$PFUNIT_VERSION" >> $GITHUB_OUTPUT
          echo "json-fortran-version=$JSON_FORTRAN_VERSION" >> $GITHUB_OUTPUT

      - name: Setup - Python environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: "**/requirements-tests.txt"

      - name: Setup - Install Python dependencies
        run: |
          pip install -r .github/workflows/extra/requirements-tests.txt

      - name: Get pFUnit
        id: get-pfunit
        if: matrix.backend == 'cpu'
        uses: ./.github/actions/setup_pfunit
        with:
          version: ${{ steps.setup-deps.outputs.pfunit-version }}
          os: ${{ steps.setup-env.outputs.os-version }}
          compiler: ${{ matrix.compiler }}

      - name: Get JSON-Fortran
        id: get-json-fortran
        uses: ./.github/actions/setup_json-fortran
        with:
          version: ${{ steps.setup-deps.outputs.json-fortran-version }}
          os: ${{ steps.setup-env.outputs.os-version }}
          compiler: ${{ matrix.compiler }}

      - name: Build
        id: build
        env:
          PFUNIT_DIR: ${{ steps.get-pfunit.outputs.install-dir }}
        run: |
          mkdir ${{ github.workspace }}/install
          echo "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:${{ github.workspace }}/install/lib/pkgconfig" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${{ github.workspace }}/install/lib" >> $GITHUB_ENV
          echo "PATH=${{ github.workspace }}/install/bin:${PATH}" >> $GITHUB_ENV
          ./regen.sh
          ./configure FC=${FC} CC=${CC} MPIFC=mpiifx --with-pfunit=$PFUNIT_DIR --enable-real=${RP} --enable-contrib --prefix=${{ github.workspace }}/install
          make FCFLAGS="-O2 -stand f08 -warn errors `pkg-config --cflags json-fortran`" -j$(nproc) install

      - name: Test - Check
        if: matrix.backend == 'cpu'
        run: |
          make -j ${{ steps.setup-env.outputs.nproc }} check > tests/test-suite.log

      - name: Integration tests
        run: |
           chmod +x $MAKENEKO_EXEC
           cd tests/integration
           pytest --timeout 120  --max_nprocs=2 --real_precision=${RP}
           cd ../..

      - name: Archive integration test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Intel Integration test logs - ${{ matrix.os }} - ${{ matrix.compiler }} - ${{ matrix.backend }} - ${{ matrix.precision }}
          path: |
            tests/integration/logs
            tests/unit/test-suite.log
          retention-days: 1
