name: Formatting

# Controls when the action will run.
on:
#  pull_request:
#     branches: [develop,release/*,master]
  workflow_dispatch:

jobs:
  linting:
    name: "Formatter (findent)"
    runs-on: ubuntu-latest
    steps:
      - name: Setup env.
        run: |
          sudo apt-get update && sudo apt-get install python-dev python3-tk
          pip install findent
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: findent
        run: |
          export FINDENT_FLAGS="-i2 -d3 -f3 -s3 -w3 -t3 -j3 -k- -Rr -c3"
          find src/ -name "*.f90" -exec bash -c 'findent < {} > {}.tmp; mv -f {}.tmp {}' \;
          git commit -a -m "findent formatting" || true
          git push
      - name: Archive linter report
        uses: actions/upload-artifact@v2
        with:
          name: findent-report
          path: findent.txt
          retention-days: 5
