name: Formatting

# Controls when the action will run.
on:
#  pull_request:
#     branches: [develop,release/*,master]
  workflow_dispatch:

jobs:
  formatting:
      name: "Formatter (findent)"
 #     description: "Check if the code is formatted according to the rules"
      runs-on: ubuntu-20.04
      steps:
        - name: Setup env.
          run: |
            sudo apt-get update && sudo apt-get install -yq python3-dev python3-pip python3-tk
            pip install findent
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 1
        - name: Check Format
          run: |
            export FINDENT_FLAGS="-i2 -d3 -f3 -s3 -w3 -t3 -j3 -k- -Rr -c3 --openmp=0"
            find src/ -iname "*.f90" -exec bash -c 'findent < {} > {}.tmp; mv -f {}.tmp {}' \;
            if [ ! -z "$(git diff --exit-code)" ]; then
              >&2 echo "Formatting rules violated"
              git diff --exit-code
              exit 1
            fi
